/* The Monte Carlo cinema. A rule set (a genome of 18 numbers) generates films from the archive by chance; a fixed critic scores
   each film from its embeddings (CLIP for pictures and words, CLAP for music); rule sets that make good films survive, cross and
   mutate. The same file runs offline (node) and in the browser.   Material: monte/material.json (monte/pack.py). */
(function (root) {
  // ---- the material
  function dec(b64, n) { const bin = typeof atob === 'function' ? atob(b64) : Buffer.from(b64, 'base64').toString('binary'); const a = new Int8Array(bin.length);
    for (let k = 0; k < bin.length; k++) a[k] = bin.charCodeAt(k) << 24 >> 24; const d = a.length / n, out = [];
    for (let r = 0; r < n; r++) { const v = new Float32Array(d); let s = 0; for (let k = 0; k < d; k++) { v[k] = a[r * d + k]; s += v[k] * v[k]; } s = Math.sqrt(s) || 1; for (let k = 0; k < d; k++) v[k] /= s; out.push(v); } return out; }
  const dot = (a, b) => { let s = 0; for (let k = 0; k < a.length; k++) s += a[k] * b[k]; return s; };
  function load(M) { M.SE = dec(M.shotEmb, M.shots.length); M.CT = dec(M.cardText, M.cards.length); M.LT = dec(M.lineEmb, M.lines.length);
    M.cardIx = new Map(M.cards.map((s, k) => [s, k])); M.plain = M.shots.map((s, k) => k).filter(k => !M.shots[k].title);
    M.opening = M.cards.filter(k => /present|produced|picture|productions?|films?\b/i.test(M.shots[k].text) && !/\bend\b/i.test(M.shots[k].text));
    M.ending = M.cards.filter(k => /\bthe end\b|^end\b|einde/i.test(M.shots[k].text));
    M.middle = M.cards.filter(k => !M.opening.includes(k) && !M.ending.includes(k)); return M; }
  // ---- the rules: each gene in [0,1], read through its range
  const GENES = [['acts', 3, 7, 'acts'], ['shots', 2, 5, 'shots per act'], ['card', 0, 1, 'a card opens an act'], ['voice', 0, 2.5, 'spoken lines per act'],
    ['wJudge', 0, 3, 'trust the judge'], ['wMatch', 0, 3, 'match cuts'], ['target', .55, .9, 'how alike a cut'], ['wText', 0, 3, 'cards borne out'], ['wVoice', 0, 3, 'words fit pictures'],
    ['ret', 0, 1, 'return to the first image'], ['exc', 0, 1, 'the last act breaks'], ['dur', 1.8, 3.6, 'seconds a shot'], ['silence', 0, .6, 'silent acts'],
    ['wRole', 0, 2, 'rule of three'], ['bw', 0, 1, 'black and white allowed'], ['temp', .05, .6, 'chance'], ['wColour', 0, 2, 'colour holds'], ['hold', 2.2, 3.8, 'seconds a card']];
  const val = (g, k) => { const [, lo, hi] = GENES[k]; return lo + (hi - lo) * g[k]; };
  const G = name => GENES.findIndex(x => x[0] === name);
  function rng(seed) { let a = seed >>> 0; return () => { a |= 0; a = a + 0x6D2B79F5 | 0; let t = Math.imul(a ^ a >>> 15, 1 | a); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t; return ((t ^ t >>> 14) >>> 0) / 4294967296; }; }
  function pick(R, xs, score, temp) { const s = xs.map(score), mx = Math.max(...s), w = s.map(v => Math.exp((v - mx) / Math.max(.02, temp))), t = w.reduce((a, b) => a + b, 0); let r = R() * t;
    for (let k = 0; k < xs.length; k++) { r -= w[k]; if (r <= 0) return xs[k]; } return xs[xs.length - 1]; }
  const sample = (R, xs, n) => { const out = []; for (let k = 0; k < n; k++) out.push(xs[Math.floor(R() * xs.length)]); return [...new Set(out)]; };
  // ---- a film, generated by the rules (events: card | shot, with an optional spoken line on a shot)
  function generate(M, g, seed) {
    const R = rng(seed), v = n => val(g, G(n)), temp = v('temp'), ev = [], used = new Set(), films = new Map();
    const acts = Math.round(v('acts'));
    const op = M.opening.length ? pick(R, sample(R, M.opening, 30), k => M.shots[k].score / 10 * v('wJudge'), temp) : null;
    if (op != null) { ev.push({ kind: 'card', k: op, dur: v('hold') }); used.add(op); }
    let prev = null, roleRun = [], first = null;
    for (let a = 0; a < acts; a++) {
      let card = null;
      if (M.middle.length && (a === 0 || R() < v('card'))) {
        card = pick(R, sample(R, M.middle, 40).filter(k => !used.has(k)), k => M.shots[k].score / 10 * v('wJudge') + (prev != null ? .5 * dot(M.CT[M.cardIx.get(k)], M.SE[prev]) * v('wText') : 0), temp);
        if (card != null) { ev.push({ kind: 'card', k: card, dur: v('hold'), act: a }); used.add(card); }
      }
      const silent = R() < v('silence'), n = Math.max(1, Math.round(v('shots') + (R() - .5) * 2));
      const actShots = [];
      for (let s = 0; s < n; s++) {
        const last = a === acts - 1 && s === n - 1;
        if (last && first != null && R() < v('ret')) { ev.push({ kind: 'shot', k: first, dur: v('dur') + .6, act: a, silent, ret: true }); actShots.push(first); continue; }
        const cand = sample(R, M.plain, 160).filter(k => !used.has(k));
        const cen = actShots.length ? actShots.map(k => M.SE[k]) : null;
        const k = pick(R, cand, c => { const S = M.shots[c]; let sc = S.score / 10 * v('wJudge');
          if (prev != null) { const sim = dot(M.SE[prev], M.SE[c]); sc -= Math.abs(sim - v('target')) * 3 * v('wMatch') / 3; sc -= Math.abs(S.colour - M.shots[prev].colour) * v('wColour') * .5; }
          if (card != null && s < 2) sc += dot(M.CT[M.cardIx.get(card)], M.SE[c]) * 4 * v('wText');
          if (roleRun.length >= 1 && roleRun[roleRun.length - 1] === S.role) sc += .35 * v('wRole');
          if (S.colour < .12) sc -= (1 - v('bw')) * 1.2;
          if (films.get(S.film)) sc -= .8 * films.get(S.film);
          if (last && cen && v('exc') > .5) sc += (1 - Math.max(...cen.map(e => dot(e, M.SE[c])))) * 2 * v('exc');   // the exception: unlike the act
          return sc; }, temp);
        if (k == null) continue;
        const e = { kind: 'shot', k, dur: v('dur') * (.85 + R() * .3), act: a, silent }; ev.push(e); used.add(k); actShots.push(k);
        if (first == null) first = k; films.set(M.shots[k].film, (films.get(M.shots[k].film) || 0) + 1);
        roleRun.push(M.shots[k].role); if (roleRun.length > 3) roleRun.shift(); prev = k;
      }
      // spoken lines this act, each laid on a shot it suits
      const lines = Math.floor(v('voice') + R()), shotsHere = ev.filter(e => e.kind === 'shot' && e.act === a && !e.line);
      for (let l = 0; l < lines && shotsHere.length; l++) {
        const e = shotsHere[Math.floor(R() * shotsHere.length)]; if (e.line != null) continue;
        e.line = pick(R, sample(R, M.lines.map((_, k) => k), 220), L => dot(M.LT[L], M.SE[e.k]) * 4 * v('wVoice'), temp);
        const ln = M.lines[e.line]; e.dur = Math.max(e.dur, ln.t1 - ln.t0 + .6);
      }
    }
    if (M.ending.length) { const end = pick(R, sample(R, M.ending, 20), k => M.shots[k].score / 10, temp); ev.push({ kind: 'card', k: end, dur: v('hold'), end: true }); }
    // the score: the music whose mood is nearest the cards' words
    const cm = ev.filter(e => e.kind === 'card').map(e => M.cardMood[M.cardIx.get(e.k)]).filter(Boolean);
    const mood = cm.length ? cm[0].map((_, j) => cm.reduce((s, x) => s + x[j], 0) / cm.length) : M.moods.map(() => 0);
    const music = pick(R, M.music.map((_, k) => k), k => { const x = M.music[k].mood; return cos(x, mood) * 3; }, .3);
    return { seed, ev, music, mood };
  }
  const cos = (a, b) => { let s = 0, x = 0, y = 0; for (let k = 0; k < a.length; k++) { s += a[k] * b[k]; x += a[k] * a[k]; y += b[k] * b[k]; } return s / (Math.sqrt(x * y) || 1); };
  // ---- the critic: fixed, from the embeddings; each part in [0,1]
  const CRITIC = { anderson: .28, cuts: .14, cards: .14, voice: .1, structure: .14, variety: .08, pace: .06, music: .06 };
  function critic(M, f, W = CRITIC) {
    const ev = f.ev, shots = ev.filter(e => e.kind === 'shot'), cards = ev.filter(e => e.kind === 'card'), P = {};
    P.anderson = ev.length ? ev.reduce((s, e) => s + M.shots[e.k].score, 0) / ev.length / 10 : 0;
    let c = [], cl = [], vl = [];
    for (let k = 1; k < ev.length; k++) if (ev[k].kind === 'shot' && ev[k - 1].kind === 'shot') { const s = dot(M.SE[ev[k - 1].k], M.SE[ev[k].k]); c.push(Math.exp(-(((s - .72) / .12) ** 2))); }
    P.cuts = c.length ? c.reduce((a, b) => a + b, 0) / c.length : 0;
    for (let k = 0; k < ev.length; k++) if (ev[k].kind === 'card' && !ev[k].end && M.cardIx.has(ev[k].k)) {
      const nx = ev.slice(k + 1, k + 3).filter(e => e.kind === 'shot'); if (!nx.length) continue;
      cl.push(Math.min(1, Math.max(0, (Math.max(...nx.map(e => dot(M.CT[M.cardIx.get(ev[k].k)], M.SE[e.k]))) - .17) / .12))); }
    P.cards = cl.length ? cl.reduce((a, b) => a + b, 0) / cl.length : 0;
    for (const e of shots) if (e.line != null) vl.push(Math.min(1, Math.max(0, (dot(M.LT[e.line], M.SE[e.k]) - .17) / .12)));
    P.voice = vl.length ? (vl.reduce((a, b) => a + b, 0) / vl.length) * Math.min(1, vl.length / 3) : 0;
    let three = 0; for (let k = 2; k < shots.length; k++) if (M.shots[shots[k].k].role === M.shots[shots[k - 1].k].role && M.shots[shots[k].k].role === M.shots[shots[k - 2].k].role) three = 1;
    const chapters = ev.filter(e => e.kind === 'card' && !e.end && !M.opening.includes(e.k)).length;   // the film is told in chapters, in the archive's own cards
    P.structure = (cards.length && M.opening.includes(ev[0].k) ? .2 : 0) + (ev.length && ev[ev.length - 1].end ? .2 : 0) + (shots.some(e => e.ret) ? .2 : 0) + .2 * three + .2 * Math.min(1, chapters / 2);
    P.variety = shots.length ? new Set(shots.map(e => M.shots[e.k].film)).size / shots.length : 0;
    const T = ev.reduce((s, e) => s + e.dur, 0); f.seconds = T; P.pace = T < 55 ? T / 55 : T > 95 ? Math.max(0, 1 - (T - 95) / 40) : 1;
    P.music = f.music != null ? Math.max(0, cos(M.music[f.music].mood, f.mood)) : 0;
    f.parts = P; f.score = Object.entries(W).reduce((s, [k, w]) => s + w * (P[k] || 0), 0); return f.score;
  }
  // ---- evolution: rule sets that make good films survive, cross and mutate
  function evolve(M, opts = {}) {
    const R = rng(opts.seed || 1), P = opts.pop || 24, K = opts.films || 6, ELITE = opts.elite || 6, W = opts.critic || CRITIC;
    let pop = opts.start || Array.from({ length: P }, () => GENES.map(() => R())), gen = 0, history = [], best = null;
    function rate(g) { const fs = []; for (let k = 0; k < K; k++) { const f = generate(M, g, Math.floor(R() * 1e9)); critic(M, f, W); fs.push(f); } fs.sort((a, b) => b.score - a.score);
      return { g, fit: (fs[0].score + fs[1].score + fs[2].score) / 3, film: fs[0] }; }
    function step() { const rated = pop.map(rate).sort((a, b) => b.fit - a.fit);
      if (!best || rated[0].film.score > best.film.score) best = { g: rated[0].g, film: rated[0].film, gen };
      history.push({ gen, best: rated[0].fit, mean: rated.reduce((s, r) => s + r.fit, 0) / rated.length, g: rated[0].g.slice(), film: rated[0].film.score });
      const elite = rated.slice(0, ELITE).map(r => r.g), sigma = .14 * Math.pow(.97, gen); const next = elite.map(g => g.slice());
      while (next.length < P) { const a = elite[Math.floor(R() * elite.length)], b = elite[Math.floor(R() * elite.length)];
        next.push(a.map((x, k) => { let y = R() < .5 ? x : b[k]; if (R() < .35) { y += (R() + R() + R() - 1.5) * sigma * 2; } return Math.min(1, Math.max(0, y)); })); }
      pop = next; gen++; return history[history.length - 1]; }
    return { step, get best() { return best; }, get history() { return history; }, get pop() { return pop; } };
  }
  const api = { load, generate, critic, evolve, GENES, CRITIC, val, dot };
  if (typeof module !== 'undefined') module.exports = api; else root.MonteCinema = api;
})(this);
