"""Write chemistry/compounds.json: a name and a reading for each poem's natural compound, and one new compound per
poem, synthesised from it by the bench's reactions (flip, condense, break, crystallise, read). Every compound is
checked against the bench's rules: valence, and which bonds two elements can hold.
    python3 lab/chemistry/author.py
Notation: atoms are a symbol and a tag (Ba1), bonds  -  single cut · = shared time (dissolve, superimposition) ·
# rhyme (same image type) · ~ resonance (signs a shot can flip between) · > break (movement-image into time-image) ·
. loose (no cut, an association); after | the sound ligands, Sym@atom:IN|OFF|OUT.
"""
import json, os, re
HERE = os.path.dirname(os.path.abspath(__file__))
C = json.load(open(os.path.join(HERE, 'chem-data.json'))); A = C['atoms']; BO = C['bond_order']
SYM = {a['sym']: n for n, a in A.items()}; LIG = {l['sym'] for l in C['ligands']}

def parse(s):
    body, _, ligs = s.partition('|'); atoms, bonds, seen = [], [], {}
    for tok in body.split():
        m = re.fullmatch(r'([A-Z][a-z])(\d+)([-=#~>.])([A-Z][a-z])(\d+)', tok)
        if not m: raise ValueError('bad bond ' + tok)
        for sym, tag in ((m[1], m[2]), (m[4], m[5])):
            k = sym + tag
            if k not in seen: seen[k] = 1; atoms.append({'k': k, 'el': SYM[sym]})
        bonds.append([m[1] + m[2], m[4] + m[5], m[3]])
    for j, tok in enumerate(ligs.split()):
        m = re.fullmatch(r'([A-Z][a-z])@([A-Z][a-z]\d+):(IN|OFF|OUT)', tok)
        if not m or m[1] not in LIG or m[2] not in seen: raise ValueError('bad ligand ' + tok)
        atoms.append({'k': 'l%d' % j, 'el': m[1], 'lig': m[3]}); bonds.append(['l%d' % j, m[2], ':'])
    return atoms, bonds

def check(atoms, bonds, name):
    el = {a['k']: a['el'] for a in atoms}; used = {k: 0 for k in el}
    for a, b, t in bonds:
        if t == ':': continue
        x, y = A[el[a]], A[el[b]]
        if t == '#' and x['col'] != y['col']: raise ValueError(f'{name}: {x["sym"]}#{y["sym"]} rhyme needs one image type')
        if t == '=' and x['regime'] != y['regime']: raise ValueError(f'{name}: {x["sym"]}={y["sym"]} shared time needs one regime')
        if t == '~' and y['n'] not in [f['to'] for f in x['flips']] and x['n'] not in [f['to'] for f in y['flips']]: raise ValueError(f'{name}: {x["sym"]}~{y["sym"]} are not neighbours')
        if t == '>' and not (x['regime'] == 'movement' and y['regime'] == 'time'): raise ValueError(f'{name}: {x["sym"]}>{y["sym"]} break runs movement → time')
        used[a] += BO[t]; used[b] += BO[t]
    for k, u in used.items():
        if el[k] in A and u > A[el[k]]['valence']: raise ValueError(f'{name}: {A[el[k]]["sym"]} holds {u} > valence {A[el[k]]["valence"]}')

W = {
 '01': dict(name='Fire-escape crystal', reading='A body held in attitude (Ba) cannot finish its small act: the reading never reaches the turned back (Ls). The room folds into a picture of itself (Ma) and empties into any-space-whatever (As), and there the chain breaks (>) into a crystal of limpid and opaque (Lo): the vape haze, where actual and virtual trade places. It ends on peaks of the present (Pp), the two falls as one instant. Her voice binds OUT to the haze.',
   new=dict(name='Ember', formula='Ba1-Ma2 Ma2-As3 As3>Lo4 Lo4~Mf5 Mf5-Sn6 | Po@Lo4:OUT Wh@Sn6:OFF', lineage='lift the failed act (Ls) and the double present (Pp) · Lo resonates into mirrors face to face (Mf) · break with the catalyst "Unnatural voice" → sonsign (Sn)', reading='Leave the act out entirely. The haze crystallises twice: limpid and opaque, then mirrors face to face, so the two falling bodies become each other’s reflections. The chain ends in a sonsign, a whisper OFF that no action answers. The last light is the ember, and it is heard, not seen. Ma keeps one free valence: an open place for a shot of the poet at the glass.')),
 '02': dict(name='Headlights-off resonance', reading='The most resonant of the fourteen: three of its five bonds are ~, so every shot sits on a hinge. The charged object (Fe, the headlights, the scream) resonates with the symbol that carries it (Sb). A solid perceiver (So) resonates with the face (Ic), and weak destiny (Wd) resonates with sheets of the past (Sp). The poem is a fall whose images keep threatening to become their neighbours. Her voice binds to the fetish.',
   new=dict(name='Dilated sun', formula='Fe1~Sb2 Sb2-So3 So3~Ic4 Ic4>Sp5 Sp5~Wd6 Sb2.Op7 | Po@Fe1:OUT Rs@Ic4:OUT', lineage='cut the face’s bond to weak destiny and break it straight into sheets of the past (Ic > Sp) · a loose opsign (Op) hung off the symbol · a riser under the face', reading='“After a day of life dilated at the sun”: let the face (Ic) break directly into sheets of the past, and let a pure optical situation (Op, the sun itself) hang loosely off the symbol, never cut in, only associated. The riser under the face is the scream traveling inward.')),
 '03': dict(name='Tambourine salt', reading='Sheets of the past (Sp) are cut against a fetish (Fe, the tambourine), bound to an originary world (Or, the empty temple and the storm under everything). From that world one branch breaks into an opsign (Op): nothing to do but see the empty choir stands. Another branch carries a symbol (Sb) into a movement of world (Mw), the storm taking what was called goods. Two ends: one pure sight, one moving world.',
   new=dict(name='Lightning-sealed', formula='Sp1-Fe2 Fe2#Or3 Or3>Op4 Or3-Mw5 Mw5~Rd6 | Po@Op4:OUT Ht@Or3:IN', lineage='the fetish rhymes with its own genesis (Fe # Or, same impulse column) · lift the symbol · Mw resonates into rich dream (Rd) · a hit IN on the originary world', reading='Make the tambourine and the storm the same kind of image: Fe # Or, a rhyme cut on the impulse column, the object and the world it comes from. The storm resonates into rich dream (Rd), a waking that can be told from sleeping. The lightning is a hit IN, placed in her next silence.')),
 '04': dict(name='Twice-vowed opsign', reading='Built outward from the pure optical situation (Op, 40 seconds of the suite’s cut): shoreline, ash, a trail. The opsign (valence 1) holds one bond only, to a plastic figure (Pl). That leads to the limit of the large form (Ll), where situation → action gives out, then a demark (Dm), the thing that breaks the pattern. Last come the fetish (Fe) and the originary world (Or). Followed twice, the vow comes back as an object and a world.',
   new=dict(name='Nevermore dimer', formula='Op1-Pl2 Pl2-Ll3 Ll3-Dm4 Dm4#Mk5 Mk5-Sp6 Sp6#Pp7 | Po@Op1:OUT Dr@Sp6:OUT', lineage='flip the fetish back to its mark (Fe ~ Mk, then the rhyme Dm # Mk) · condense the tail into the chronosign pair Sp # Pp · a drone under the sheets', reading='“A trail followed twice”: pair the demark with its mark (Dm # Mk), the habit and the break in it as a rhyme cut. Then pair the sheets of the past with the peaks of the present (Sp # Pp), memory and simultaneity as one image type. The molecule is a dimer: the same trail twice, once remembered and once all at once.')),
 '05': dict(name='Bloodline radical', reading='An originary world (Or, the earth to inherit) shares its time with the dividual (Dv, the people who made him) in a double bond (=), a superimposition of world and crowd. From the world a line runs through the limit of the large form (Ll) to a fetish (Fe, the name). There it breaks into the cinema of the brain (Br), where naming the stars after people becomes thought, and ends on a symbol (Sb).',
   new=dict(name='Star-naming ester', formula='Or1=Dv2 Or1-Fe3 Fe3>Br4 Br4-Sb5 Br4.Le6 Sb5~Mk7 | Po@Or1:OUT Co@Dv2:OFF', lineage='lift the large form’s limit · the symbol resonates into mark (Mk) · read it: a lectosign (Le) bound loosely to the brain · a chorus OFF with the crowd', reading='“Beware of me”: the brain (Br) is read, the lectosign bound loosely, so the image becomes something to read and not only to see. The stars carry names as marks (Mk), and a chorus stands OFF with the dividual: the people who made him, heard but unseen.')),
 '06': dict(name='Atlantean chain', reading='A long, open chain with a single ring of resonance. Sheets of the past (Sp) cut to any-space-whatever (As), then weak destiny (Wd), then the quotidian (Qu), everyday life made both ridiculous and heroic. The quotidian resonates with the milieu (Mi), where the city is a world that makes actions, and the chain ends in a movement of world (Mw): the city rising from the water as a dance.',
   new=dict(name='Marble seed', formula='Sp1-As2 As2>Se3 Se3~Lo4 Se3-Mi5 Mi5~Qu6 Qu6-Mw7 | Po@Se3:OUT Bd@Mi5:OUT', lineage='weak destiny breaks through any-space-whatever into the crystal’s genesis, seed and environment (Se) · Se resonates with limpid and opaque (Lo) · a bed under the milieu', reading='“A city born in unison out of the purest of fictions”: the gates become seed and environment (Se), a crystal that grows its own world. The rising city resonates between limpid and opaque. The milieu keeps its quotidian, and a bed lies under it: safe, together, one.')),
 '07': dict(name='Eleven-petal ion', reading='A dance (Mw) shares its time with the theatrical figure (Th) in a double bond: the stage and the moving world are one. From the dance, a face (Ic, eyes wide shut, chin nested) leads to a symbol (Sb, the volume, the open mic). The symbol breaks into limpid and opaque (Lo) and ends in restrained dream (Rs): turned up, but never quite woken.',
   new=dict(name='Turned-up tautomer', formula='Mw1=Rd2 Mw1-Th3 Th3~Pf4 Pf4-Lo5 Lo5-Sn6 Pf4-Ic7 | Po@Th3:OUT Lp@Mw1:OUT St@Sn6:IN', lineage='the dance shares its time with rich dream instead of theatre (Mw = Rd) · theatre resonates into powers of the false (Pf) · end on a sonsign · a loop OUT under the dance, a stem IN at the end', reading='One open mic at a time: the stage (Th) tips into the powers of the false (Pf), where performance becomes the truth of the story told. The chain ends on a sonsign with a stem IN, so the music is on screen. Volume turned up is literally the picture’s sound.')),
 '08': dict(name='Dance-floor spirit', reading='The dividual (Dv, the dance floor) breaks into limpid and opaque (Lo), the soul leaving a body that stays visible. The crystal holds a face (Ic), the face gives onto any-space-whatever (As, the open field at a planet’s equator), and that breaks again into the cinema of the brain (Br). It ends on a movement of world (Mw), wandering eyes and thoughts. Two breaks: a double crossing into the time-image.',
   new=dict(name='Equator vapour', formula='Dv1>Lo2 Lo2-Ga3 Ga3~Lq4 Ga3-As5 As5>Br6 Br6#Ba7 | Po@Lo2:OUT Tx@As5:OFF', lineage='flip the face three steps down to gaseous perception (Ic → Dv → Lq → Ga) · the brain rhymes with bodies of attitude (Br # Ba) · a texture OFF over the field', reading='Let the soul be seen as gaseous perception (Ga), perception without a centre that resonates with liquid (Lq). The field keeps its any-space-whatever, and the brain rhymes with a body of attitude (Br # Ba): the body left on the floor, “can now just be”.')),
 '09': dict(name='Three-call polymer', reading='Perception migrates (Lq) and is held (So): the lover seen and seeing. It breaks into bodies of gest (Bg, the calls as rituals), then passes the limit of the large form (Ll), where no action answers. It reaches any-space-whatever (As) and ends on an index of equivocity (Ie), the same act explained by two worlds. Heard, yet.',
   new=dict(name='Yet, heard (trimer)', formula='So1~Lq2 Lq2>Sn3 So1-Bg4 Bg4#Ba5 Ba5-Ie6 | Po@So1:OUT Fv@Sn3:OFF', lineage='perception resonates (So ~ Lq) · liquid breaks straight into a sonsign: the call itself · gest rhymes with attitude (Bg # Ba) · a found voice OFF', reading='Three calls before leaving, built as three units. Held and migrating perception resonate. A sonsign carries a found voice OFF: the call, heard and unanswered. Then bodies of gest rhyme with bodies of attitude, the ritual of calling and the tired body after it. The index of equivocity stays at the end: love was real, or was not.')),
 '10': dict(name='Morning dot-by-dot', reading='Restrained dream (Rs) shares its time with any-space-whatever (As) in a double bond: the ride as a half-waking space. Any-space-whatever resonates with enfeeblement (En), then comes the originary world (Or), a solid perceiver (So) and a symbol (Sb): the magic that still exists. Night is replaced by morning through small, hinged steps.',
   new=dict(name='Moon-settling', formula='Rs1=Mw2 Mw2-As3 As3~En4 En4-Qu5 Qu5>Pp6 As3.Sb7 | Po@As3:OUT Dr@Rs1:OUT', lineage='restrained dream shares its time with the movement of world (Rs = Mw): the ride itself moving · the originary world lifts · enfeeblement opens onto its own genesis, the quotidian (En − Qu) · the quotidian breaks into peaks of the present · the symbol only loosely held', reading='“The moon settles and the tease of distant stars subsides”: the half-waking and the moving world overlap in a double bond, as the ride carries the night. Enfeeblement gives onto the quotidian, a new morning’s ordinariness, and the quotidian breaks into peaks of the present, dot by dot, several mornings at once. The magic, the symbol, is held loosely and never cut in.')),
 '11': dict(name='Temple course', reading='The originary world (Or) breaks into an opsign (Op, a chilly morning seen) and resonates with any-space-whatever (As). That space breaks into the cinema of the brain (Br, “moments of great clarity”), then sheets of the past (Sp), then seed and environment (Se), where the temple assembles one course at a time. Her voice binds to the seed.',
   new=dict(name='Clarity lattice', formula='Or1>Op2 Or1~As3 As3>Se4 Se4-Br5 Br5-Sp6 Se4#Mf7 | Po@Se4:OUT Bd@Br5:OUT', lineage='any-space-whatever breaks directly into the seed (As > Se) · the seed rhymes with mirrors face to face (Se # Mf), the whole hyalosign column · a bed under clarity', reading='A lattice rather than a chain: the seed (Se) sits at the centre with three bonds, rhyming with mirrors face to face so the temple builds itself in reflections. Clarity (Br) sits on the bed. “A heart at peace” is the saturated molecule, with its one open valence at the opsign’s start: morning is still cold.')),
 '12': dict(name='Brotherhood ester', reading='The limit of the large form (Ll: decades later, there is nothing left to do) breaks into bodies of gest (Bg: hugs, football, laughter as ritual). Then come the dividual (Dv, brotherhood), strong destiny (Sd, recollections that bring them home), the face (Ic), and a final break into sheets of the past (Sp). The least action and the most people.',
   new=dict(name='Laughter hydrate', formula='Dv1-Bg2 Bg2#Ba3 Dv1-Sd4 Sd4#Wd5 Wd5>Sp6 Dv1.Ic7 | Po@Dv1:OUT Co@Dv1:IN', lineage='drop the large form’s limit · gest rhymes with attitude (Bg # Ba) · strong destiny rhymes with weak (Sd # Wd), recollection holding and loosening · a chorus IN with the brotherhood', reading='“Less time for words, more space for laughter”: the brotherhood (Dv) sits at the centre with a chorus IN, the laughter on screen. The ritual rhymes with the resting body, and recollection loosens from strong destiny to weak before it breaks into the sheets of the past. The face is only loosely held: smiles with no reason.')),
 '13': dict(name='Orbital heart', reading='An opsign (Op: a corner cafe, only seen) opens onto the dividual (Dv). That breaks into bodies of attitude (Ba), then restrained dream (Rs), which resonates with weak destiny (Wd), and ends on an index of equivocity (Ie): the promise of the heart as an act with two readings. Close orbits, counted.',
   new=dict(name='Promise isomer', formula='Op1-Ic2 Ic2~Dv3 Dv3>Ba4 Ba4-Rs5 Rs5~Rd6 Rd6-Ie7 | Po@Ic2:OUT Sg@Rs5:OUT', lineage='the same atoms rearranged: the opsign now opens on a face (Ic ~ Dv) · restrained dream resonates into rich dream (Rs ~ Rd) · a song OUT under the dreaming', reading='An isomer of the natural compound: nearly the same atoms, bonded to begin with the face, “notice me”. Dream widens from restrained to rich, so the fantasy can be told from the cafe. A song carries it OUT: “I could celebrate forever.”')),
 '14': dict(name='Weather-door', reading='Forking paths (Fp) branch two ways. One way leads to any-space-whatever (As), which shares its time with the theatrical figure (Th). The other leads to an index of equivocity (Ie), which breaks into sheets of the past (Sp) and ends on a symbol (Sb, a New Testament as it ends). Everything learns to be weather, then a door.',
   new=dict(name='Genesis door', formula='Fp1-As2 As2-Th3 Th3~Pf4 Fp1-Ie5 Ie5>Sp6 Sp6#Pf7 Sp6.Le8 | Po@Th3:OUT Ht@Ie5:IN', lineage='theatre resonates into powers of the false (Th ~ Pf) · sheets of the past rhyme with powers of the false (Sp # Pf) · read it: the lectosign loose on the sheets · a hit IN at the door', reading='The door is a lectosign: the whole molecule becomes readable (Le, loose) at the end, a genesis as it ends. Powers of the false appear twice, from the theatre and from the sheets of the past, so what is told and what is remembered both become fabulation. The hit IN is the door closing.')),
}
out = []
for p in C['poems']:
    w = W[p['n']]; nat = p['natural']
    check(nat['atoms'], nat['bonds'], p['n'] + ' natural')
    atoms, bonds = parse(w['new']['formula']); check(atoms, bonds, p['n'] + ' ' + w['new']['name'])
    out.append({'poem': p['n'], 'natural': {'name': w['name'], 'reading': w['reading']},
                'new': [{'id': p['n'] + '-new-1', 'poem': p['n'], 'kind': 'synthesis', 'name': w['new']['name'], 'lineage': w['new']['lineage'], 'reading': w['new']['reading'], 'atoms': atoms, 'bonds': bonds}]})
json.dump(out, open(os.path.join(HERE, 'compounds.json'), 'w'), indent=1, ensure_ascii=False)
print('ok', len(out))
