/* Program theories for the word ↔ clip binding mockups. One entry per numbered drawing.
   Each entry is a Naurian theory: the bet, its unit and core verb, entities, operations, the invariant,
   the affordances it gives a person, how it fails, what a change in requirements would do, and the
   primitives it is built from (PRIM ids). The page computes every comparison from `p`. */
window.FAMILIES = {
  P1: { name: 'Concordance', bet: 'The word is the unit. Meaning lives in single words and their recurrences.', lab: 'Videotext poem map · word-level sound actions' },
  P2: { name: 'Voice Clock', bet: 'Her breath cuts the picture. The rhythm is already in the voice.', lab: 'Sound desk mix law · 0.68 s median pause · CUT timeline' },
  P3: { name: 'Scale Ladder', bet: 'The poem is nested, so the film is nested. See word, line, stanza and whole at once.', lab: 'Nothing yet · 88 beats have no stanza grouping' },
  P4: { name: 'Audition', bet: 'Choosing among plenty is the work. Make comparison fast and leave reasons behind.', lab: 'Cutting room floor · candidate-ranks.json' },
  P5: { name: 'Association Field', bet: 'Meaning is a space. The sequence is a path walked through it.', lab: 'CLIP emb.npy · 15,149 shots · sign families' },
  P6: { name: 'Branch Garden', bet: 'There is no single right cut. Keep forks, compare them, merge the best.', lab: 'The four cuts: suite · scenes · cineosis · drift' },
  P7: { name: 'Loop Wheel', bet: 'Watching is the interface. Never stop playing; stop the wheel on the one that works.', lab: 'WAG Tempest · monte · 474 pack loops' },
  P8: { name: 'Template Press', bet: 'Make the rule once and apply it everywhere. The machine drafts, a person corrects.', lab: 'Nothing yet · rank weights are the only rule' },
  P9: { name: 'Strata', bet: 'Text, clips, sound, places and time are layers on one clock. A cut is a vertical line through all of them.', lab: 'Sound desk tracks · CUT lanes' },
};

window.CATS = {
  grain: 'Text grain · how much of the poem is held',
  act: 'Text act · what you do to the words',
  topo: 'Clip topology · how the clips are laid out',
  bind: 'Binding · how words connect to clips',
  time: 'Time · how the clock is shown',
  move: 'Motion · how you travel',
  judge: 'Judgment · how clips are compared',
  make: 'Making · how a sequence gets built',
};

window.PRIM = {
  w:   ['grain', 'word', 'a single spoken word, with its time on the clock'],
  ph:  ['grain', 'phrase', 'a run of words inside a line'],
  ln:  ['grain', 'line', 'one line of the poem, usually one breath'],
  st:  ['grain', 'stanza', 'a group of lines'],
  ps:  ['grain', 'passage', 'a stretch of the poem larger than a stanza'],
  mn:  ['grain', 'mentions', 'every occurrence of the same word or line'],
  sel: ['act', 'select', 'mark words as the current subject'],
  pin: ['act', 'pin', 'fix a clip to one occurrence so nothing can move it'],
  flt: ['act', 'filter', 'words narrow the pool; nothing is deleted'],
  exc: ['act', 'exclude', 'struck words remove what they would bring'],
  msk: ['act', 'mask', 'hide or dim the text outside the selection'],
  brk: ['act', 'bracket', 'draw bounds around a span to make it a unit'],
  str: ['act', 'stretch', 'widen a span or its picture'],
  pch: ['act', 'pinch', 'narrow a span or its picture'],
  lop: ['act', 'loop', 'repeat a span so it can be judged again'],
  one: ['topo', 'single', 'one clip at full size'],
  row: ['topo', 'row', 'clips side by side in order'],
  grd: ['topo', 'grid', 'clips in rows and columns'],
  lst: ['topo', 'list', 'clips as rows beside text, like a shelf'],
  stk: ['topo', 'stack', 'clips or pages piled, one on top'],
  lyr: ['topo', 'layers', 'parallel planes, each a kind of material'],
  rng: ['topo', 'ring', 'clips on a closed circle'],
  spi: ['topo', 'spiral', 'clips on an opening curve; distance means rank'],
  tre: ['topo', 'tree', 'clips as leaves under choices'],
  rad: ['topo', 'radial', 'clips around a centre at equal standing'],
  clu: ['topo', 'cluster', 'clips grouped into kinds'],
  net: ['topo', 'web', 'clips as nodes joined by relations'],
  strip: ['topo', 'film strip', 'frames on a sprocketed strip'],
  nst: ['topo', 'nested scales', 'the same material at several zoom levels'],
  fun: ['topo', 'funnel', 'stages that narrow the pool'],
  fan: ['topo', 'fan', 'clips spread from one point like cards in a hand'],
  b11: ['bind', 'one to one', 'a word or span holds exactly one clip'],
  b1n: ['bind', 'one to many', 'a span offers several candidates'],
  bnn: ['bind', 'many to many', 'every word against every clip'],
  bsq: ['bind', 'span to sequence', 'a span maps to an ordered run of clips'],
  btm: ['bind', 'template', 'a pattern of slots binds to any span'],
  phd: ['time', 'playhead', 'a line at now, shared by text and clips'],
  rul: ['time', 'ruler', 'a time axis with ticks'],
  wav: ['time', 'waveform', 'the voice drawn as sound'],
  bea: ['time', 'beat marks', 'cut points found in the sound'],
  win: ['time', 'window', 'a movable range of time'],
  lens: ['time', 'lens', 'a magnified range over a compressed whole'],
  sld: ['move', 'slide', 'move sideways through a sequence'],
  rot: ['move', 'rotate', 'turn a ring or fan to bring the next forward'],
  zm:  ['move', 'zoom', 'change scale in place'],
  stp: ['move', 'step', 'advance one item at a time'],
  drl: ['move', 'drill', 'descend into a child level'],
  exp: ['move', 'expand', 'open or close a container'],
  tab: ['move', 'tabs', 'switch between named piles'],
  foc: ['judge', 'focus', 'one item large, its context small'],
  dim: ['judge', 'dim', 'grey out what is not chosen'],
  ab:  ['judge', 'A/B', 'two candidates for the same span'],
  syn: ['judge', 'synced', 'several clips played on one clock'],
  gho: ['judge', 'ghost', 'one clip over another, translucent'],
  mos: ['judge', 'mosaic', 'the whole pool at once, judged by eye'],
  rnk: ['judge', 'rank order', 'position encodes the score'],
  gat: ['make', 'gather', 'collect clips into a holding place'],
  bld: ['make', 'build', 'append clips to a sequence one by one'],
  aut: ['make', 'auto', 'the machine proposes the sequence'],
  sty: ['make', 'style', 'one treatment applied to many clips'],
};

window.THEORIES = [
  { id: 36, n: 'Word Focus', f: 'P1', bet: 'The strongest binding is the smallest: one word summons one image.', verb: 'focus', ent: ['word', 'shot', 'glow'],
    ops: ['<person> [focuses] <word>', '<word> [summons] <shot>', '<shot> [plays-under] <word>.t0…t1'], inv: 'Focus is exclusive: one focused word, one shot.',
    aff: ['tap a word to see its image', 'hear the word while its shot plays', 'move focus to the next word'], fail: 'A function word is focused: offer the nearest content word.', chg: 'Allow two focused words and it becomes 037.', p: ['w', 'sel', 'foc', 'one', 'b11'] },
  { id: 37, n: 'Phrase Spotlight', f: 'P1', bet: 'Phrases carry images better than words; a phrase fans into candidates.', verb: 'spotlight', ent: ['phrase', 'line', 'candidate'],
    ops: ['<person> [drags-across] {word} → <phrase>', '<phrase> [dims] rest of <line>', '<phrase> [fans-to] {candidate}×3'], inv: 'Dimmed words stay audible and keep their times.',
    aff: ['drag across words to make a phrase', 'see three candidates at once', 'read the phrase against the dimmed line'], fail: 'The phrase crosses a beat: split it or ask.', chg: 'With more candidates it becomes 182.', p: ['ph', 'sel', 'msk', 'dim', 'b1n', 'row'] },
  { id: 38, n: 'Line Spotlight', f: 'P1', bet: 'The line is the natural unit of a cut: one breath, one image choice.', verb: 'light', ent: ['line', 'candidate'],
    ops: ['<person> [lights] <line>', '<line> [fans-to] {candidate}', '<person> [seats] one'], inv: 'A lit line is bound whole; no word inside it holds its own seat.',
    aff: ['pick a line', 'compare three for it', 'seat one'], fail: 'A long line needs two images: split it at a pause.', chg: 'Allow word seats inside and it becomes 036.', p: ['ln', 'sel', 'msk', 'b1n', 'row'] },
  { id: 39, n: 'Stanza Mask', f: 'P3', bet: 'Context sets the reading: mask everything but the stanza so choices serve it.', verb: 'mask', ent: ['stanza', 'poem', 'shot'],
    ops: ['<stanza> [masks] <poem>', '<stanza> [offers] {shot}'], inv: 'The mask is view only; it never edits text or seats.',
    aff: ['isolate one stanza', 'see its shots in a row', 'unmask to check against the whole'], fail: 'Stanza bounds are unknown: fall back to beats.', chg: 'Mask at line grain and it becomes 038.', p: ['st', 'msk', 'dim', 'foc', 'row', 'b1n'] },
  { id: 40, n: 'Passage Zoom', f: 'P3', bet: 'Attention narrows in steps: page, then passage, then clips.', verb: 'zoom', ent: ['page', 'passage', 'shot'],
    ops: ['<page> [zooms-to] <passage>', '<passage> [opens] {shot}'], inv: 'Zoom keeps place: zooming out returns to the same spot.',
    aff: ['zoom into a passage', 'see only its clips', 'zoom out without losing place'], fail: 'Deep zoom hides neighbours: keep a thumbnail of the page.', chg: 'Add more levels and it becomes 070.', p: ['ps', 'zm', 'drl', 'foc', 'b1n'] },
  { id: 41, n: 'Word Filter', f: 'P1', bet: 'A word is a query: the pool shrinks to what the word allows.', verb: 'filter', ent: ['word', 'pool', 'filter'],
    ops: ['<word> [filters] <pool>', '{shot} matching [survive]'], inv: 'Filtering hides, never deletes; clearing restores exactly.',
    aff: ['make a word the filter', 'stack filters', 'clear to restore'], fail: 'Nothing survives: show the nearest, flagged.', chg: 'Filter by sign instead of word; the verb stays.', p: ['w', 'flt', 'fun', 'row'] },
  { id: 42, n: 'Phrase Exclude', f: 'P1', bet: 'Saying what an image must not be is as useful as saying what it must be.', verb: 'exclude', ent: ['word', 'strike', 'pool'],
    ops: ['<person> [strikes] <word>', '<struck word> [removes] its shots from <pool>'], inv: 'Exclusions stay visible (the strike is drawn) and reversible.',
    aff: ['strike words', 'watch the pool grey out', 'unstrike'], fail: 'Everything is struck: say so, keep one.', chg: 'Make strikes global and they become a stop-list.', p: ['w', 'ph', 'exc', 'flt', 'dim', 'row'] },
  { id: 43, n: 'Line Loop', f: 'P7', bet: 'Hear the line again and again until the image fits.', verb: 'loop', ent: ['line', 'loop', 'shot'],
    ops: ['<line> [loops]', '{shot} [tries] under <loop>', '<person> [keeps] one'], inv: 'Loop bounds sit on word edges.',
    aff: ['loop a line', 'swap clips under it', 'leave the loop'], fail: 'Fatigue: cap the passes, then step on.', chg: 'Loop the phrase and it becomes 210.', p: ['ln', 'lop', 'row', 'b1n'] },
  { id: 44, n: 'Stanza Stack', f: 'P3', bet: 'Stanzas are pages you flip; each carries its own clips.', verb: 'flip', ent: ['stanza', 'stack', 'shot'],
    ops: ['{stanza} [stack]', '<top stanza> [links] {shot}'], inv: 'Only the top stanza is live; order is the poem\'s.',
    aff: ['flip stanzas', 'see each stanza\'s links', 'keep one stanza on top while choosing'], fail: 'Buried stanzas are forgotten: show seat coverage on each edge.', chg: 'Unstack and it becomes 049.', p: ['st', 'stk', 'lst', 'b1n'] },
  { id: 45, n: 'Passage Mosaic', f: 'P4', bet: 'See a passage\'s whole pool at once and choose by eye.', verb: 'scan', ent: ['passage', 'mosaic', 'shot'],
    ops: ['<passage> [spreads] {shot} as mosaic', '<person> [picks] one'], inv: 'The mosaic is ordered by rank, never shuffled.',
    aff: ['scan a grid', 'pick with one tap', 'read the rank from position'], fail: 'Too many tiles: cap at 12 live, rest still.', chg: 'Split per line and it becomes 182.', p: ['ps', 'grd', 'mos', 'rnk', 'b1n'] },
  { id: 46, n: 'Word Pin', f: 'P1', bet: 'A pin is a promise: this word must show this image.', verb: 'pin', ent: ['occurrence', 'pin', 'shot'],
    ops: ['<person> [pins] <shot> [to] <occurrence>', '<pin> [survives] re-ranking'], inv: 'A pin outranks every machine choice.',
    aff: ['pin', 'unpin', 'see pinned words marked'], fail: 'Two pins overlap in time: the later word wins, the other warns.', chg: 'Pin at phrase grain and it becomes 177 with a span.', p: ['w', 'pin', 'one', 'b11'] },
  { id: 47, n: 'Phrase Pinch', f: 'P2', bet: 'Tighten the phrase and the cut tightens with it.', verb: 'pinch', ent: ['phrase', 'span', 'clip'],
    ops: ['<person> [pinches] <phrase>', '{clip} [re-fit] to the narrower span'], inv: 'The voice never changes length; only picture bounds move.',
    aff: ['pinch a span narrower', 'see clips re-fit', 'release to commit'], fail: 'Pinched below one word: snap to the word.', chg: 'The opposite gesture is 048.', p: ['ph', 'pch', 'row', 'bsq'] },
  { id: 48, n: 'Line Stretch', f: 'P2', bet: 'A picture can hold past its words, into the pause that follows.', verb: 'stretch', ent: ['line', 'pause', 'shot'],
    ops: ['<person> [stretches] <line>.picture', '<shot> [holds] into <pause>'], inv: 'A stretch ends at the next breath; it never covers the next line\'s words.',
    aff: ['drag a picture longer', 'let an image linger', 'feel the pause'], fail: 'No pause follows: refuse, show why.', chg: 'Stretch at word grain and it becomes 209.', p: ['ln', 'str', 'one', 'rul'] },
  { id: 49, n: 'Stanza Filmstrip', f: 'P3', bet: 'Text column and film column, row for row.', verb: 'align', ent: ['stanza', 'line', 'frame'],
    ops: ['<line> [aligns-with] <frame>', '<stanza> [becomes] <strip>'], inv: 'One frame per line, in the same order.',
    aff: ['read and see side by side', 'scroll both together', 'spot an empty frame'], fail: 'A line needs two frames: the strip must allow doubles.', chg: 'Drop the text and it is 067.', p: ['st', 'strip', 'lst', 'bsq'] },
  { id: 50, n: 'Passage Build', f: 'P8', bet: 'A passage builds itself into a sequence; you watch and stop it.', verb: 'build', ent: ['passage', 'sequence', 'clip'],
    ops: ['<passage> [builds] <sequence> clip by clip', '<newest clip> [glows]'], inv: 'The build appends in poem order.',
    aff: ['start a build', 'accept or reject each new clip', 'undo the last'], fail: 'The build runs ahead of judgment: pause after each.', chg: 'Let the machine finish and it becomes 284.', p: ['ps', 'bld', 'aut', 'bsq', 'row'] },
  { id: 51, n: 'Branch Tree', f: 'P6', bet: 'One word opens alternatives; choosing a branch is choosing a film.', verb: 'branch', ent: ['word', 'branch', 'shot'],
    ops: ['<word> [branches-to] {alternative}', '<person> [takes] <branch>'], inv: 'Branches not taken still exist.',
    aff: ['open alternatives from a word', 'take a branch', 'come back to another'], fail: 'Too many branches: cap at three per node.', chg: 'Add depth and it becomes 053.', p: ['w', 'tre', 'drl', 'b1n'] },
  { id: 52, n: 'Split Branch', f: 'P6', bet: 'Some alternatives deserve their own sub-choice; depth is uneven.', verb: 'split', ent: ['node', 'branch', 'shot'],
    ops: ['<node> [splits]', '<branch> [marks] the choice'], inv: 'Every leaf traces one path from the line.',
    aff: ['split one option further', 'leave others shallow', 'see the chosen path'], fail: 'Lopsided trees hide options: show leaf counts.', chg: 'Force even depth and it becomes 054.', p: ['ln', 'tre', 'drl', 'b1n'] },
  { id: 53, n: 'Deep Tree', f: 'P6', bet: 'Decisions nest deeply; the film is a path from root to leaf.', verb: 'descend', ent: ['path', 'node', 'leaf'],
    ops: ['<person> [descends] <tree>', '<path> [selects] <leaf shot>'], inv: 'One path per leaf; the path is the reason.',
    aff: ['descend decision by decision', 'read a choice as its path', 'back up one level'], fail: 'Deep paths are lost: breadcrumb the path.', chg: 'Flatten to one level and it is 051.', p: ['tre', 'nst', 'drl', 'b1n'] },
  { id: 54, n: 'Balanced Tree', f: 'P6', bet: 'Structure mirrors syntax: the line at the root, words split evenly down to shots.', verb: 'parse', ent: ['line', 'word', 'shot'],
    ops: ['<line> [parses-to] {word}', '{word} [leafs-to] <shot>'], inv: 'Every word under the root reaches a shot.',
    aff: ['see the line\'s grammar', 'choose per branch', 'see balance at a glance'], fail: 'Grammar is not the image logic: allow re-grouping.', chg: 'Remove hierarchy and it becomes 187.', p: ['ln', 'tre', 'bsq', 'drl'] },
  { id: 55, n: 'Radial Tree', f: 'P5', bet: 'Alternatives radiate equally from the line; none is first.', verb: 'radiate', ent: ['line', 'spoke', 'shot'],
    ops: ['<line> [radiates] {shot}', '<person> [marks] one'], inv: 'Spokes are unordered; angle means nothing.',
    aff: ['see all options as equals', 'mark one', 'add a spoke'], fail: 'Equality hides the ranking: tint by score.', chg: 'Let distance mean rank and it becomes 058.', p: ['ln', 'rad', 'b1n'] },
  { id: 56, n: 'Radial Fan', f: 'P7', bet: 'Flip through candidates like cards in a hand.', verb: 'fan', ent: ['line', 'card', 'shot'],
    ops: ['<person> [rotates] <fan>', '<front card> [plays]'], inv: 'One card is in front at a time.',
    aff: ['thumb through options', 'see the next peeking', 'play the front card'], fail: 'Cards behind are unseen: show count.', chg: 'Close the fan to a circle and it is 057.', p: ['ln', 'fan', 'rot', 'one'] },
  { id: 57, n: 'Circular Ring', f: 'P7', bet: 'Candidates orbit the line; turn until the right one sits at the mark.', verb: 'orbit', ent: ['line', 'ring', 'mark'],
    ops: ['<ring> [rotates]', '<shot at mark> [binds] to <line>'], inv: 'The ring is closed: no first, no last.',
    aff: ['spin the ring', 'stop on one', 'see every option at once'], fail: 'Ring too large: sample 12.', chg: 'Open the ring by rank and it is 058.', p: ['ln', 'rng', 'rot', 'foc', 'b1n'] },
  { id: 58, n: 'Spiral', f: 'P7', bet: 'Rank as distance: spiral out from best to worst.', verb: 'unwind', ent: ['line', 'spiral', 'rank'],
    ops: ['{shot} [placed] by rank along <spiral>', '<person> [unwinds] outward'], inv: 'Distance from centre equals rank.',
    aff: ['see best nearest', 'unwind for more', 'stop on one'], fail: 'Tail items are tiny: enlarge on hover.', chg: 'Remove rank and it is 057.', p: ['ln', 'spi', 'rot', 'rnk', 'b1n'] },
  { id: 59, n: 'Constellation', f: 'P5', bet: 'Similarity as distance: stars near the line mean the most.', verb: 'place', ent: ['line', 'star', 'distance'],
    ops: ['{shot} [placed] by similarity to <line>', '<person> [picks] a star'], inv: 'Position is computed, never hand-dragged.',
    aff: ['see how close each clip is', 'pick the nearest or a far one on purpose', 'watch stars move when the line changes'], fail: 'Clumping: spread with jitter, keep order.', chg: 'Group into kinds and it is 060.', p: ['ln', 'net', 'clu', 'rnk', 'b1n'] },
  { id: 60, n: 'Cluster Map', f: 'P5', bet: 'Choose a kind of image before an image.', verb: 'group', ent: ['cluster', 'shot', 'line'],
    ops: ['{shot} [group-into] {cluster}', '<person> [enters] <cluster>', '<person> [picks] <shot>'], inv: 'A shot belongs to one cluster at a time.',
    aff: ['see the kinds on offer', 'enter a kind', 'pick inside it'], fail: 'Clusters meaningless: label each by its sign or top word.', chg: 'Draw edges between clusters and it is 086.', p: ['ln', 'clu', 'drl', 'b1n'] },
  { id: 61, n: 'Cascading Drawers', f: 'P3', bet: 'Each line is a drawer holding its clips; open one at a time.', verb: 'open', ent: ['line', 'drawer', 'clip'],
    ops: ['<line> [owns] <drawer>', '<person> [opens] <drawer>'], inv: 'Drawers keep poem order.',
    aff: ['open a line\'s drawer', 'see its sequence', 'close it'], fail: 'Closed drawers hide empties: mark coverage on each.', chg: 'Only one open at a time and it is 062.', p: ['ln', 'lst', 'exp', 'bsq'] },
  { id: 62, n: 'Accordion', f: 'P3', bet: 'One line expanded, the rest folded; focus without losing the list.', verb: 'unfold', ent: ['line', 'fold', 'clip'],
    ops: ['<person> [unfolds] <line>', '<others> [fold]'], inv: 'Exactly one line is unfolded.',
    aff: ['unfold a line', 'see its clips in place', 'fold it back'], fail: 'Jumpy layout: animate height.', chg: 'Allow many open and it is 061.', p: ['ln', 'lst', 'exp', 'foc'] },
  { id: 63, n: 'Tabs', f: 'P4', bet: 'Familiar piles: sort the pool into named tabs.', verb: 'switch', ent: ['tab', 'pile', 'clip'],
    ops: ['<pool> [sorts-into] {tab}', '<person> [switches] <tab>'], inv: 'A clip lives in one tab.',
    aff: ['switch pile', 'see a grid per pile', 'pick'], fail: 'Tabs hide comparison across piles.', chg: 'Show all piles at once and it is 060.', p: ['tab', 'grd', 'flt'] },
  { id: 64, n: 'Stacked Cards', f: 'P4', bet: 'One at a time, full size: judge each on its own.', verb: 'deal', ent: ['card', 'deck', 'verdict'],
    ops: ['<deck> [deals] <card>', '<person> [keeps-or-discards] <card>'], inv: 'Every card gets a verdict before the next.',
    aff: ['see one clip large', 'keep or toss', 'move to the next'], fail: 'No comparison: pair with 134.', chg: 'Spread the deck and it is 045.', p: ['stk', 'one', 'stp', 'rnk'] },
  { id: 65, n: 'Carousel', f: 'P7', bet: 'One centred, neighbours shrinking: browse by sliding.', verb: 'slide', ent: ['centre', 'neighbour', 'clip'],
    ops: ['<person> [slides] <carousel>', '<centre> [plays]'], inv: 'Only the centre plays with sound.',
    aff: ['slide left or right', 'see what\'s next', 'play the centre'], fail: 'Edges hide rank: badge each.', chg: 'Keep the text above and it is 203.', p: ['row', 'sld', 'foc', 'one'] },
  { id: 66, n: 'Sliding Window', f: 'P7', bet: 'A window over the sequence moves with you; context either side.', verb: 'slide', ent: ['window', 'sequence', 'clip'],
    ops: ['<window> [slides] along <sequence>', '<clip in window> [plays]'], inv: 'The window is always the same width.',
    aff: ['slide through the cut', 'see before and after', 'stop on a clip'], fail: 'Window too small: show a minimap.', chg: 'Bind to words and it is 203.', p: ['row', 'win', 'sld', 'foc'] },
  { id: 67, n: 'Film Strip', f: 'P2', bet: 'The cut as a strip with sprockets: speak film\'s own language.', verb: 'frame', ent: ['strip', 'frame', 'clip'],
    ops: ['<cut> [renders-as] <strip>', '<person> [selects] <frame>'], inv: 'Strip order is time order.',
    aff: ['read the cut as frames', 'select one', 'see empty frames'], fail: 'Durations are lost: scale frames by length.', chg: 'Add scales and it is 068.', p: ['strip', 'row', 'sel', 'bsq'] },
  { id: 68, n: 'Multi-scale Strip', f: 'P3', bet: 'Several strips at several scales, aligned.', verb: 'align', ent: ['strip', 'scale', 'frame'],
    ops: ['<cut> [renders-at] {scale}', '<selection> [echoes] across scales'], inv: 'A selection at one scale shows at all scales.',
    aff: ['see detail and whole together', 'select at any scale', 'follow the echo'], fail: 'Too many rows: max three scales.', chg: 'Keep one scale and a lens and it is 069.', p: ['strip', 'nst', 'zm', 'rul'] },
  { id: 69, n: 'Timeline Lens', f: 'P2', bet: 'The waveform is the map; a lens over it opens the clips beneath.', verb: 'lens', ent: ['waveform', 'lens', 'clip'],
    ops: ['<lens> [slides] over <waveform>', '<lensed range> [opens] {clip}'], inv: 'The lens range is shown both on the wave and in the clips.',
    aff: ['sweep a lens over the voice', 'see the clips of that range', 'resize the lens'], fail: 'Silence has nothing to see: snap lens to speech.', chg: 'Remove the wave and it is 066.', p: ['wav', 'lens', 'rul', 'b1n'] },
  { id: 70, n: 'Zoom Levels', f: 'P3', bet: 'The same film at three zoom levels, drilled top-down.', verb: 'drill', ent: ['level', 'range', 'clip'],
    ops: ['<level> [contains] <level>', '<person> [drills] into a range'], inv: 'Coarse levels are derived from fine seats.',
    aff: ['drill from whole to detail', 'see where you are in the whole', 'climb back'], fail: 'Summary frames lie: show coverage bars.', chg: 'Flatten to two and it is 130.', p: ['nst', 'zm', 'drl', 'rul'] },
  { id: 76, n: 'Funnel', f: 'P4', bet: 'Stages narrow the pool until one remains.', verb: 'narrow', ent: ['pool', 'stage', 'winner'],
    ops: ['<pool> [passes] {stage}', '<last stage> [yields] <winner>'], inv: 'Every stage records what it removed and why.',
    aff: ['see the pool shrink', 'inspect each stage', 'take the winner'], fail: 'The pool is weak: the funnel ends in "forage again", not a forced pick.', chg: 'Put a person at each stage and it is 064 repeated.', p: ['fun', 'flt', 'rnk', 'one'] },
  { id: 81, n: 'Concordance', f: 'P1', bet: 'Every appearance of the line, listed, with its clips beside it.', verb: 'concord', ent: ['line', 'occurrence', 'clip'],
    ops: ['<line> [gathers] {occurrence}', '{occurrence} [pairs-with] {clip}'], inv: 'An occurrence is a time, not just a string.',
    aff: ['see every time a line recurs', 'compare what each shows', 'make the rhyme on purpose'], fail: 'No recurrences: fall back to near-matches.', chg: 'At word grain it is 287.', p: ['mn', 'lst', 'grd', 'bnn'] },
  { id: 86, n: 'Association Web', f: 'P5', bet: 'Everything the line touches, drawn as a web.', verb: 'associate', ent: ['line', 'edge', 'clip'],
    ops: ['<line> [links] {clip}', '<person> [draws] <edge>'], inv: 'Hand edges are kept apart from computed ones.',
    aff: ['see all associations', 'draw a new one', 'follow an edge'], fail: 'Hairball: show the k=12 nearest.', chg: 'Group the leaves and it is 060.', p: ['ln', 'net', 'rad', 'b1n'] },
  { id: 91, n: 'Layers', f: 'P9', bet: 'Text, clips, audio, places and time are planes; a pin passes through all.', verb: 'pierce', ent: ['layer', 'pin', 'item'],
    ops: ['{layer} [stack] on one clock', '<pin> [pierces] every <layer> at t'], inv: 'All layers share one clock.',
    aff: ['see all material at one moment', 'move the pin through time', 'lift a layer out'], fail: 'Planes occlude: fan them apart on hover.', chg: 'Flatten to lanes and it is 285.', p: ['lyr', 'phd', 'stk', 'syn'] },
  { id: 96, n: 'Story Builder', f: 'P8', bet: 'Outline on the left, candidates above, the film assembles below.', verb: 'assemble', ent: ['outline', 'candidate', 'sequence'],
    ops: ['<outline item> [calls] {candidate}', '<person> [drops] <candidate> into <sequence>'], inv: 'The sequence follows outline order.',
    aff: ['see the story as bullets', 'drop clips into the film', 'watch the film grow'], fail: 'Outline and poem disagree: poem wins.', chg: 'Let the machine drop and it is 284.', p: ['ln', 'lst', 'bld', 'bsq', 'row'] },
  { id: 114, n: 'Multi-Scale', f: 'P3', bet: 'The row above is the zoom of a point in the row below.', verb: 'magnify', ent: ['row', 'scale', 'clip'],
    ops: ['<fine row> [magnifies] a cell of <coarse row>'], inv: 'The magnified cell is highlighted in both rows.',
    aff: ['see a detail and its place', 'shift the magnified cell', 'compare neighbours'], fail: 'Lose track of scale: label the ratio.', chg: 'Add a third row and it is 315.', p: ['nst', 'zm', 'row', 'rul'] },
  { id: 115, n: 'Map View', f: 'P5', bet: 'Clips placed on a free map, the chosen one centred.', verb: 'map', ent: ['map', 'clip', 'line'],
    ops: ['{clip} [placed] on <map>', '<person> [centres] one'], inv: 'Map positions persist between visits.',
    aff: ['arrange clips spatially', 'centre one', 'remember where things are'], fail: 'Arbitrary layout: seed positions from similarity.', chg: 'Compute positions and it is 059.', p: ['net', 'clu', 'sel', 'foc'] },
  { id: 119, n: 'Matched Windows', f: 'P4', bet: 'Two candidates, same span, same clock: compare honestly.', verb: 'match', ent: ['candidate', 'window', 'clock'],
    ops: ['<A>, <B> [play] on one <clock>', '<scrub> [moves] both'], inv: 'Both windows always show the same time.',
    aff: ['play two against the words', 'scrub both together', 'choose'], fail: 'Different lengths: loop the shorter, flag it.', chg: 'Overlay them and it is 135.', p: ['ab', 'syn', 'rul', 'phd'] },
  { id: 120, n: 'Stack Compare', f: 'P4', bet: 'Candidates stacked like transparencies; flip through at the same spot.', verb: 'flip', ent: ['sheet', 'stack', 'spot'],
    ops: ['{candidate} [stack]', '<person> [flips] up or down'], inv: 'The spot in time stays fixed while flipping.',
    aff: ['flip through options in place', 'see thickness as count', 'pull one out'], fail: 'Lower sheets unseen: fan on hover.', chg: 'Make sheets translucent and it is 135.', p: ['stk', 'lyr', 'ab', 'stp'] },
  { id: 124, n: 'Ripple Browse', f: 'P7', bet: 'The centre clip swells; neighbours ripple smaller as you move.', verb: 'ripple', ent: ['centre', 'ripple', 'row'],
    ops: ['<cursor> [swells] nearest clip', '<neighbours> [shrink] by distance'], inv: 'Size falls off with distance only.',
    aff: ['skim a long row', 'see detail under the cursor', 'keep context'], fail: 'Jitter: smooth the swell.', chg: 'Fixed centre and it is 065.', p: ['row', 'sld', 'foc', 'zm'] },
  { id: 125, n: 'Stepped Play', f: 'P7', bet: 'Play the sequence in steps; each step hands off to the next.', verb: 'step', ent: ['step', 'clip', 'handoff'],
    ops: ['<clip> [plays]', '<end> [hands-off] to next <clip>'], inv: 'Only one clip plays at a time.',
    aff: ['watch the cut in order', 'pause between steps', 'jump back one'], fail: 'Gaps between steps: preload the next.', chg: 'Continuous play and it is 204.', p: ['stp', 'row', 'phd', 'bsq'] },
  { id: 129, n: 'Mosaic Compare', f: 'P4', bet: 'All candidates visible, one enlarged; compare by eye.', verb: 'enlarge', ent: ['mosaic', 'candidate', 'focus'],
    ops: ['{candidate} [tile]', '<person> [enlarges] one'], inv: 'The enlarged tile keeps its place in the grid.',
    aff: ['see everything', 'enlarge one without leaving', 'pick'], fail: 'GPU load: one live, others still.', chg: 'Two enlarged and it is 119.', p: ['grd', 'mos', 'foc', 'ab'] },
  { id: 130, n: 'Focus + Context', f: 'P3', bet: 'The current clip large in the strip, the whole compressed around it.', verb: 'focus', ent: ['strip', 'focus', 'context'],
    ops: ['<strip> [compresses] outside <focus>', '<focus> [slides] along'], inv: 'The whole film always fits on screen.',
    aff: ['see now and all', 'slide the focus', 'jump anywhere'], fail: 'Compressed parts unreadable: tint by coverage.', chg: 'Add the wave and it is 069.', p: ['strip', 'foc', 'lens', 'rul'] },
  { id: 134, n: 'A/B Loop', f: 'P4', bet: 'Two candidates alternate on the same loop until one wins.', verb: 'alternate', ent: ['A', 'B', 'loop'],
    ops: ['<loop> [alternates] <A> and <B>', '<person> [prefers] one'], inv: 'Each pass is the same span of voice.',
    aff: ['hear the line with A then B', 'prefer', 'bring in the next challenger'], fail: 'Order bias: randomise which comes first.', chg: 'A tournament of loops becomes 076.', p: ['ab', 'lop', 'syn'] },
  { id: 135, n: 'Ghost Overlay', f: 'P4', bet: 'Lay one clip over another, half-visible, to feel the difference.', verb: 'overlay', ent: ['base', 'ghost', 'opacity'],
    ops: ['<ghost> [overlays] <base>', '<person> [slides] <opacity>'], inv: 'Both play on the same clock.',
    aff: ['see two images in one frame', 'slide between them', 'judge composition'], fail: 'Muddy: allow a wipe instead of fade.', chg: 'Side by side and it is 119.', p: ['gho', 'ab', 'syn', 'rul'] },
  { id: 139, n: 'Shot List', f: 'P4', bet: 'A plain list: thumbnail and reasons, one row each.', verb: 'list', ent: ['row', 'shot', 'reason'],
    ops: ['{shot} [lists] with <reason>', '<person> [selects] a row'], inv: 'Rows sorted by rank; the reason is always visible.',
    aff: ['read why each clip is there', 'select a row', 'scan fast'], fail: 'Text-heavy: collapse reasons to one chip.', chg: 'Add a time rail and it is 317.', p: ['lst', 'sel', 'rnk'] },
  { id: 140, n: 'Cluster View', f: 'P5', bet: 'Clips in loose piles by kind; the chosen one outlined.', verb: 'pile', ent: ['pile', 'clip'],
    ops: ['{clip} [piles] by kind', '<person> [outlines] one'], inv: 'Piles are computed; the choice is personal.',
    aff: ['see the kinds', 'choose inside a pile', 'compare piles'], fail: 'Piles overlap: separate them.', chg: 'Bind to a word and it is 344.', p: ['clu', 'sel'] },
  { id: 176, n: 'Ribbon Bind', f: 'P2', bet: 'A phrase unrolls as a ribbon of clips that bends with the voice.', verb: 'unroll', ent: ['phrase', 'ribbon', 'clip'],
    ops: ['<phrase> [unrolls-as] <ribbon>', '<ribbon> [bends] at word edges'], inv: 'The ribbon spans exactly the phrase.',
    aff: ['see a phrase as film', 'grab a fold', 'feel the timing'], fail: 'Curves hide timing: flatten on demand.', chg: 'Flatten and it is 191.', p: ['ph', 'strip', 'bsq', 'b1n'] },
  { id: 177, n: 'Pin to Shot', f: 'P1', bet: 'Drop a pin from a word straight into one shot.', verb: 'drop', ent: ['word', 'pin', 'shot'],
    ops: ['<word> [drops] <pin> into <shot>'], inv: 'One pin, one shot.',
    aff: ['pin from the text', 'see the thread down', 'lift it'], fail: 'Pinned shot disappears from pool: keep it and warn.', chg: 'Same verb as 046, drawn from the word side.', p: ['w', 'pin', 'b11', 'one'] },
  { id: 178, n: 'Flow Chain', f: 'P8', bet: 'The word points to the next link in a growing chain.', verb: 'chain', ent: ['word', 'link', 'slot'],
    ops: ['<word> [calls] <next slot>', '<person> [fills] <slot>'], inv: 'A chain has one open slot at its end.',
    aff: ['extend the film one link', 'see what comes next', 'fill the dashed slot'], fail: 'Chain breaks: re-link.', chg: 'Fill automatically and it is 284.', p: ['w', 'row', 'bld', 'bsq'] },
  { id: 179, n: 'Layer Couple', f: 'P9', bet: 'A word reaches down through stacked layers to the one it means.', verb: 'reach', ent: ['word', 'layer', 'clip'],
    ops: ['<word> [reaches] a <layer>', '<layer> [surfaces] its clip'], inv: 'A word selects one layer at a time.',
    aff: ['choose depth', 'see layers behind', 'bring one forward'], fail: 'Back layers illegible: offset them.', chg: 'Add all material kinds and it is 091.', p: ['w', 'lyr', 'stk', 'b1n'] },
  { id: 180, n: 'Arc Connect', f: 'P5', bet: 'Arcs from words to clips show which words own which image.', verb: 'arc', ent: ['word', 'arc', 'clip'],
    ops: ['<word> [arcs-to] <clip>'], inv: 'Arcs never cross when order is kept.',
    aff: ['see ownership', 'redraw an arc', 'notice an unowned clip'], fail: 'Crossings: reorder or allow them visibly.', chg: 'One arc per word and it is 187.', p: ['w', 'net', 'row', 'b1n'] },
  { id: 181, n: 'Tree Couple', f: 'P6', bet: 'One word opens three shots as siblings.', verb: 'offer', ent: ['word', 'sibling', 'shot'],
    ops: ['<word> [offers] {sibling}'], inv: 'Siblings are equal alternatives for the same span.',
    aff: ['see three versions', 'pick', 'keep the others as forks'], fail: 'More than three: page them.', chg: 'Add depth and it is 053.', p: ['w', 'tre', 'b1n'] },
  { id: 182, n: 'Matrix Bind', f: 'P4', bet: 'Every word against every candidate in a grid.', verb: 'cross', ent: ['word', 'candidate', 'cell'],
    ops: ['{word} × {candidate} [form] <matrix>', '<person> [marks] <cell>'], inv: 'At most one marked cell per word row.',
    aff: ['see the whole choice space', 'mark cells', 'spot empty rows'], fail: 'Large matrix: show only the top 3 columns.', chg: 'One word only and it is 037.', p: ['w', 'bnn', 'grd', 'sel'] },
  { id: 183, n: 'Focus Lens', f: 'P1', bet: 'The focused word drives one clip; the others fade.', verb: 'lens', ent: ['word', 'lens', 'clip'],
    ops: ['<word> [lenses] its <clip>', '<others> [fade]'], inv: 'Unfocused words stay readable, only paler.',
    aff: ['focus by word', 'see neighbours faded', 'move the lens'], fail: 'Fading hides context: keep 40% opacity.', chg: 'Two lenses and it is 119.', p: ['w', 'foc', 'dim', 'lens', 'one'] },
  { id: 184, n: 'Sequence Bracket', f: 'P2', bet: 'Bracket a span of words; it becomes a sequence of clips.', verb: 'bracket', ent: ['bracket', 'span', 'sequence'],
    ops: ['<person> [brackets] <span>', '<span> [becomes] <sequence>'], inv: 'Brackets never overlap.',
    aff: ['draw bounds on the text', 'see its sequence', 'adjust a bracket end'], fail: 'Bracket mid-word: snap.', chg: 'Nest brackets and it is 211.', p: ['ph', 'brk', 'bsq', 'row'] },
  { id: 185, n: 'Fork Couple', f: 'P6', bet: 'A word forks into two versions; the film can go either way.', verb: 'fork', ent: ['word', 'fork', 'version'],
    ops: ['<word> [forks] two <version>'], inv: 'Both versions stay playable.',
    aff: ['make a fork', 'play each', 'merge back'], fail: 'Forks multiply: age out unused.', chg: 'Three ways and it is 181.', p: ['w', 'tre', 'fan', 'b1n'] },
  { id: 186, n: 'Clip Basket', f: 'P8', bet: 'Collect clips for a word into a basket; decide later.', verb: 'gather', ent: ['word', 'basket', 'clip'],
    ops: ['<person> [drops] <clip> into <basket>', '<basket> [belongs-to] <word>'], inv: 'A basket is not a seat until emptied into the cut.',
    aff: ['collect without deciding', 'add with +', 'empty into the film'], fail: 'Baskets overflow: cap at 6.', chg: 'Auto-fill baskets and it is 287.', p: ['w', 'gat', 'row', 'bld'] },
  { id: 187, n: 'Parallel Lines', f: 'P1', bet: 'Each word gets its own line to its own clip.', verb: 'assign', ent: ['word', 'line', 'clip'],
    ops: ['{word} [assign] one <clip> each'], inv: 'One clip per word, in order.',
    aff: ['read the line down', 'see each word\'s clip', 'swap one'], fail: 'Words too fast for clips: merge short words.', chg: 'Let a word have many and it is 189.', p: ['w', 'lst', 'b11'] },
  { id: 188, n: 'Ring Attach', f: 'P7', bet: 'The whole line at the centre; its clips on a ring around it.', verb: 'attach', ent: ['line', 'ring', 'clip'],
    ops: ['<line> [attaches] {clip} on <ring>'], inv: 'Ring order follows the line.',
    aff: ['see the line and all its clips', 'turn to one', 'play around'], fail: 'Order unclear on a ring: number them.', chg: 'Unordered and it is 055.', p: ['ln', 'rng', 'b1n'] },
  { id: 189, n: 'Grid Connect', f: 'P1', bet: 'Each word owns a column of candidates.', verb: 'column', ent: ['word', 'column', 'candidate'],
    ops: ['<word> [owns] <column>', '<person> [marks] one per column'], inv: 'One mark per column.',
    aff: ['choose per word', 'see depth per word', 'play the marked row'], fail: 'Uneven columns: pad with forage.', chg: 'Rotate and it is 182.', p: ['w', 'grd', 'bnn', 'b1n'] },
  { id: 190, n: 'List Couple', f: 'P1', bet: 'A checklist of words beside a list of clips.', verb: 'check', ent: ['word', 'check', 'clip'],
    ops: ['<person> [checks] <word>', '<word> [lights] its <clip>'], inv: 'Checked words are exactly the bound ones.',
    aff: ['tick words off', 'see which are bound', 'find the gaps'], fail: 'Long lists: group by line.', chg: 'Lines instead of words and it is 061.', p: ['w', 'lst', 'sel', 'b11'] },
  { id: 191, n: 'Timeline Couple', f: 'P2', bet: 'A phrase on the ruler points to the one clip that plays then.', verb: 'couple', ent: ['phrase', 'ruler', 'clip'],
    ops: ['<phrase> [sits-on] <ruler>', '<ruler position> [selects] <clip>'], inv: 'Clip and phrase share a time range.',
    aff: ['see phrase time', 'see its clip', 'scrub'], fail: 'Phrase between ticks: finer ticks.', chg: 'Add a playhead and it is 204.', p: ['ph', 'rul', 'phd', 'b11', 'row'] },
  { id: 192, n: 'Zoom Couple', f: 'P3', bet: 'A word zooms a small pair of clips into one large one.', verb: 'zoom', ent: ['word', 'group', 'clip'],
    ops: ['<word> [zooms] <group> to <clip>'], inv: 'Zoom is reversible.',
    aff: ['zoom in on a word\'s image', 'see the group it came from', 'zoom out'], fail: 'Loss of context: keep the group small nearby.', chg: 'Repeat per level and it is 070.', p: ['w', 'zm', 'drl', 'one'] },
  { id: 193, n: 'Scatter Bind', f: 'P5', bet: 'A word binds to a loose scatter; dashed lines show what it might mean.', verb: 'scatter', ent: ['word', 'dash', 'clip'],
    ops: ['<word> [scatters-to] {clip}'], inv: 'Dashes are suggestions, solid is chosen.',
    aff: ['see possibilities', 'firm one up', 'ignore the rest'], fail: 'Noise: hide beyond k.', chg: 'Group the scatter and it is 060.', p: ['w', 'net', 'clu'] },
  { id: 194, n: 'Stack to Film', f: 'P8', bet: 'A stack of chosen clips becomes a film strip in one move.', verb: 'print', ent: ['stack', 'film'],
    ops: ['<stack> [prints-to] <film>'], inv: 'Stack order becomes film order.',
    aff: ['collect a stack', 'turn it into film', 'reorder first'], fail: 'Stack order unclear: number it.', chg: 'Print automatically and it is 284.', p: ['w', 'stk', 'strip', 'bld'] },
  { id: 195, n: 'Span Map', f: 'P2', bet: 'A phrase marks a span on the bar; the bar maps down to clips.', verb: 'map', ent: ['span', 'bar', 'clip'],
    ops: ['<phrase> [marks] <span> on <bar>', '<span> [maps-to] {clip}'], inv: 'Span edges are word edges.',
    aff: ['see the span as time', 'drag an edge', 'see clips update'], fail: 'Overlapping spans: stack them.', chg: 'Add waveform and it is 069.', p: ['ph', 'rul', 'win', 'bsq'] },
  { id: 202, n: 'Stanza Track', f: 'P3', bet: 'The same line repeated, a different phrase lit each time, each with its clip.', verb: 'vary', ent: ['line', 'variant', 'clip'],
    ops: ['<line> [repeats] as {variant}', '<variant> [binds] one <clip>'], inv: 'Each variant lights a different span.',
    aff: ['see alternative readings', 'pick a reading', 'compare readings'], fail: 'Too many variants: keep 4.', chg: 'Across stanzas and it is 208.', p: ['st', 'ph', 'lst', 'b11'] },
  { id: 203, n: 'Sliding Window', f: 'P7', bet: 'A window over the words and the strip moves together.', verb: 'slide', ent: ['window', 'words', 'strip'],
    ops: ['<window> [slides] over words and <strip>'], inv: 'Text window and film window are the same time.',
    aff: ['slide the phrase', 'see its frames', 'arrow step'], fail: 'Fast slide: preload neighbours.', chg: 'Without words it is 066.', p: ['ph', 'win', 'strip', 'sld'] },
  { id: 204, n: 'Playhead Bind', f: 'P2', bet: 'The playhead is shared: where it crosses the words, it crosses the clips.', verb: 'play', ent: ['playhead', 'word', 'clip'],
    ops: ['<playhead> [crosses] <word> and <clip>'], inv: 'One playhead for text and picture.',
    aff: ['play and read', 'scrub', 'see word and clip at once'], fail: 'Drift between tracks: one clock only.', chg: 'Many tracks and it is 285.', p: ['phd', 'rul', 'row', 'b11'] },
  { id: 208, n: 'Stanza Layers', f: 'P9', bet: 'Each stanza a lane; spans on the lanes feed clips on the right.', verb: 'lane', ent: ['lane', 'span', 'clip'],
    ops: ['{stanza} [becomes] <lane>', '<span> [feeds] <clip>'], inv: 'Lanes share one ruler.',
    aff: ['see all stanzas at once', 'read spans', 'follow a span to its clip'], fail: 'Lanes crowd: collapse empty ones.', chg: 'Lanes by material and it is 285.', p: ['ln', 'lyr', 'lst', 'rul'] },
  { id: 209, n: 'Elastic Spacing', f: 'P2', bet: 'Drag a word wider and its clip gets more time.', verb: 'stretch', ent: ['word', 'space', 'clip'],
    ops: ['<person> [widens] <word>', '<clip> [gains] time'], inv: 'The voice is untouched; only the picture\'s share of time moves.',
    aff: ['give a word more image', 'feel the cut change', 'reset'], fail: 'Widening past a pause is impossible: stop at the edge.', chg: 'At line grain and it is 048.', p: ['w', 'str', 'rul', 'row'] },
  { id: 210, n: 'Loop Phrase', f: 'P7', bet: 'The phrase loops over a strip; the clip under the loop changes each pass.', verb: 'loop', ent: ['phrase', 'loop', 'strip'],
    ops: ['<phrase> [loops]', '<strip> [advances] one under it each pass'], inv: 'Loop length equals phrase length.',
    aff: ['hear the phrase over each clip', 'stop on one', 'loop longer'], fail: 'Loop too short to judge: minimum 2 s.', chg: 'At line grain and it is 043.', p: ['ln', 'lop', 'strip'] },
  { id: 211, n: 'Nested Timeline', f: 'P3', bet: 'A clip opens into its own timeline of sub-clips.', verb: 'nest', ent: ['clip', 'child', 'timeline'],
    ops: ['<clip> [opens-into] <timeline>', '<child> [edits] in place'], inv: 'The parent\'s duration bounds the children.',
    aff: ['open a clip', 'edit inside it', 'close it back'], fail: 'Deep nesting: max two levels.', chg: 'All levels at once and it is 070.', p: ['nst', 'zm', 'strip', 'drl'] },
  { id: 281, n: 'Track with Text', f: 'P1', bet: 'The word lives inside the image, attached to what moves.', verb: 'track', ent: ['word', 'object', 'track'],
    ops: ['<word> [attaches-to] <object> in <shot>', '<object> [moves]; <word> [follows]'], inv: 'The word stays on its object for its time.',
    aff: ['place a word in the frame', 'let it follow', 'detach'], fail: 'Tracking lost: freeze at last good position.', chg: 'Many words and it becomes captioning.', p: ['w', 'pin', 'one', 'b11'] },
  { id: 282, n: 'Audio Sync', f: 'P2', bet: 'The waveform above, the clips below, one cursor.', verb: 'sync', ent: ['waveform', 'cursor', 'clip'],
    ops: ['<cursor> [crosses] <waveform> and {clip}'], inv: 'Cuts line up with the wave.',
    aff: ['see the voice\'s shape', 'place cuts on it', 'scrub'], fail: 'Noisy wave: show envelope.', chg: 'Auto cut on beats and it is 283.', p: ['wav', 'phd', 'rul', 'row'] },
  { id: 283, n: 'Beat Cut', f: 'P2', bet: 'The sound finds the cuts; each beat mark is a cut point.', verb: 'cut', ent: ['beat', 'mark', 'clip'],
    ops: ['<waveform> [yields] {beat}', '{beat} [cuts] <sequence>'], inv: 'Every cut is on a mark unless unsnapped.',
    aff: ['get cut points free', 'unsnap one', 'fill clips between'], fail: 'Too metronomic: allow skipping marks.', chg: 'Breaths instead of beats; same program.', p: ['wav', 'bea', 'row', 'bsq'] },
  { id: 284, n: 'Auto Sequence', f: 'P8', bet: 'The line proposes the whole sequence; a person edits.', verb: 'propose', ent: ['line', 'draft', 'clip'],
    ops: ['<line> [proposes] <draft>', '<person> [overrides] a slot'], inv: 'A drafted seat is marked machine-made until accepted.',
    aff: ['get a full draft', 'fix one slot', 'accept'], fail: 'Samey drafts: diversity rule.', chg: 'With slots it is 289.', p: ['ln', 'aut', 'row', 'b1n'] },
  { id: 285, n: 'Story Timeline', f: 'P9', bet: 'Several lanes of material on one clock, one playhead through all.', verb: 'lane', ent: ['lane', 'block', 'playhead'],
    ops: ['{lane} [share] <clock>', '<playhead> [crosses] all'], inv: 'One clock; lanes can\'t drift.',
    aff: ['see everything playing now', 'move blocks', 'solo a lane'], fail: 'Clutter: collapse lanes.', chg: 'Lanes as planes and it is 091.', p: ['lyr', 'phd', 'rul', 'lst'] },
  { id: 286, n: 'Select by Text', f: 'P1', bet: 'Pick a word in the transcript; the clips for it appear.', verb: 'select', ent: ['transcript', 'word', 'clip'],
    ops: ['<person> [selects] <word> in <transcript>', '<word> [lists] {clip}'], inv: 'Selection is by text, never by guessing time.',
    aff: ['search by word', 'see matches', 'choose'], fail: 'No match: nearest by meaning.', chg: 'All mentions and it is 287.', p: ['w', 'sel', 'lst', 'b1n'] },
  { id: 287, n: 'Gather Mentions', f: 'P1', bet: 'One word gathers every clip it appears with.', verb: 'gather', ent: ['word', 'mention', 'clip'],
    ops: ['<word> [gathers] {mention}', '{mention} [brings] its clip'], inv: 'Gathered clips remember their source time.',
    aff: ['see every image a word has had', 'rhyme on purpose', 'avoid repeats'], fail: 'Common words gather too much: stop-list.', chg: 'Make it propagate and it becomes a rhyme rule.', p: ['w', 'mn', 'gat', 'b1n'] },
  { id: 288, n: 'Build Sequence', f: 'P8', bet: 'Each word drops its candidate straight down into the sequence.', verb: 'drop', ent: ['word', 'candidate', 'sequence'],
    ops: ['{word} [drops] <candidate> into <sequence>'], inv: 'Sequence order equals word order.',
    aff: ['build word by word', 'see the film form', 'swap one'], fail: 'Word timing too short for a clip: merge.', chg: 'Slots and roles and it is 289.', p: ['w', 'bld', 'bsq', 'row'] },
  { id: 289, n: 'Template Bind', f: 'P8', bet: 'A template of slots binds to a span and fills itself.', verb: 'template', ent: ['template', 'slot', 'span'],
    ops: ['<template> [binds-to] <span>', '<slot> [fills] from <pool> by rank'], inv: 'Re-running never overwrites a person\'s override.',
    aff: ['reuse a pattern', 'fill 88 beats fast', 'override a slot'], fail: 'Template misfits a span: skip and flag.', chg: 'Apply a look not a pattern and it is 290.', p: ['btm', 'aut', 'bsq', 'row'] },
  { id: 290, n: 'Style Apply', f: 'P8', bet: 'One treatment spreads to many clips; consistency is value.', verb: 'apply', ent: ['style', 'clip', 'target'],
    ops: ['<style> [applies-to] {clip}'], inv: 'Style never changes which clip is seated.',
    aff: ['grade many at once', 'see before and after', 'remove'], fail: 'Style fights the archive: per-clip strength.', chg: 'Style sound instead: same verb.', p: ['sty', 'fan', 'b1n'] },
  { id: 315, n: 'Multiscale View', f: 'P3', bet: 'Word above, clips in the middle, frames below: three scales at once.', verb: 'scale', ent: ['word', 'clip', 'frame'],
    ops: ['<word> [selects] a <clip>', '<clip> [unfolds] into {frame}'], inv: 'Scales stay aligned under the selection.',
    aff: ['see the word, the clip and its frames', 'pick a frame', 'move along'], fail: 'Bottom row too dense: sample.', chg: 'Two scales and it is 114.', p: ['w', 'nst', 'zm', 'rul'] },
  { id: 317, n: 'Clip Shelf', f: 'P4', bet: 'Clips on a shelf beside their text, with a time rail on the left.', verb: 'shelve', ent: ['shelf', 'rail', 'clip'],
    ops: ['{clip} [shelve] along <rail>', '<person> [selects] one'], inv: 'Shelf order is time order.',
    aff: ['browse by time', 'read what each is', 'pick'], fail: 'Long shelf: jump by rail.', chg: 'Remove the rail and it is 139.', p: ['lst', 'rul', 'sel'] },
  { id: 344, n: 'Cluster Panel', f: 'P5', bet: 'A word pulls one clip into the centre from the clusters around it.', verb: 'pull', ent: ['word', 'cluster', 'centre'],
    ops: ['<word> [pulls] <clip> to <centre>'], inv: 'The centre holds one clip.',
    aff: ['see the kinds around a choice', 'pull a new one in', 'compare with neighbours'], fail: 'Clusters too many: cap at 4.', chg: 'Without a word it is 140.', p: ['w', 'clu', 'foc'] },
];
