/* Videotext · Sheet 05 · Turn text into time (201–250).
   The poem on its clock. Views with a tick() follow the playhead live. */
(() => {
'use strict';
const V = window.VT, h = V.h, { esc, wire } = V;
const S = () => V.S;
const R = (id, name, desc, render, extra = {}) => V.register({ id, sheet: '05', name, desc, render, needs: 'text', ...extra });
const W = (o, a, b) => o.wide ? b : a;
const sel = () => S().sel;
const words = u => S().words.slice(u.a, u.b + 1);
const shotOfSeg = s => s.kind === 'mine' ? (V.shot(s.ref.shot.id) || s.ref.shot) : s.kind === 'base' ? (V.shot(s.ref.id) || s.ref) : null;
const segThumb = (s, o = {}) => { const sh = shotOfSeg(s); return sh ? h.ts(sh, { in: s.off, grade: false, cls: s.kind === 'mine' ? 'mine' : '', ...o }) : `<span class="vx none" style="${o.style || ''}${o.w ? ';--w:' + (typeof o.w === 'number' ? o.w + 'px' : o.w) : ''};display:flex;align-items:center;justify-content:center;font:800 9px/1.1 var(--sans);text-transform:uppercase;color:var(--dim);padding:2px;text-align:center">${esc(s.text || '')}</span>`; };
const pctIn = (t, t0, t1) => ((Math.max(t0, Math.min(t1, t)) - t0) / ((t1 - t0) || 1) * 100);
const cutsN = ['suite', 'scenes', 'cineosis', 'drift'];
const isSel = u => sel() && sel().a >= u.a && sel().a <= u.b;

R('201', 'Word Duration', 'Each word of the line as a block as long as it is spoken.', (box, v, o) => {
  const L = V.around('line'); const ws = words(L); const span = L.t1 - L.t0 || 1;
  box.innerHTML = `<div class="vlab">${V.fmt(L.t0)} – ${V.fmt(L.t1)} · ${ws.length} words · ${span.toFixed(1)} s</div><div style="display:flex;gap:2px;flex-wrap:${o.wide ? 'nowrap' : 'wrap'}">${ws.map(w => `<div data-sel="${w.i}.${w.i}" style="flex:${o.wide ? (w.t1 - w.t0) / span + ' 0 0' : '0 0 ' + Math.max(40, (w.t1 - w.t0) * 90) + 'px'};min-width:0;border:1.5px solid ${w.i >= sel().a && w.i <= sel().b ? 'var(--blue)' : 'var(--ink)'};background:${w.i >= sel().a && w.i <= sel().b ? 'var(--blue-soft)' : 'var(--panel)'};padding:6px 4px;cursor:pointer;overflow:hidden"><div style="font:500 13px var(--sans);white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(w.text)}</div><small style="font:500 9.5px var(--mono);color:var(--dim)">${(w.t1 - w.t0).toFixed(2)}s</small></div>`).join('')}</div>`;
});
R('202', 'Stanza Track', 'Every line of the stanza as its own track on one clock, with the shots that play under it.', (box, v, o) => {
  const P = V.around('stanza'); const lines = V.unitsIn(P.a, P.b, 'line'); const t0 = P.t0, t1 = P.t1;
  box.innerHTML = lines.map(u => { const segs = S().segs.filter(s => s.t1 > u.t0 && s.t0 < u.t1); return `<div style="display:grid;grid-template-columns:${W(o, '110px', '300px')} minmax(0,1fr);gap:8px;align-items:center;margin-bottom:4px"><span data-sel="${u.a}.${u.b}" style="cursor:pointer;font:400 ${W(o, 11, 13)}px/1.25 var(--sans);overflow:hidden;max-height:2.6em;${isSel(u) ? 'color:var(--blue)' : ''}">${esc(u.text)}</span><div style="position:relative;height:${W(o, 30, 44)}px;background:var(--box)">${segs.map(s => { const a = pctIn(Math.max(s.t0, u.t0), t0, t1), b = pctIn(Math.min(s.t1, u.t1), t0, t1); return `<div style="position:absolute;left:${a}%;width:calc(${b - a}% - 1px);top:0;bottom:0">${segThumb(s, { style: '--w:100%;aspect-ratio:auto;height:100%;border-width:1px' })}</div>`; }).join('')}</div></div>`; }).join('') + `<div style="display:grid;grid-template-columns:${W(o, '110px', '300px')} 1fr;gap:8px"><span></span><div class="vruler"><span style="left:0">${V.fmt(t0)}</span><span style="left:85%">${V.fmt(t1)}</span></div></div>`;
});
R('203', 'Sliding Window', 'A ten-second window that slides with the playhead: the words in it, and the shots.', (box, v, o) => {
  box.innerHTML = `<div data-win></div>${h.note('Press play: the window follows the reading. Paused, it sits on the playhead.')}`; draw203(box, S().t, o.wide);
}, { tick: (box, v, t) => draw203(box, t, box.classList.contains('wide')) });
function draw203(box, t, wide) {
  const k = Math.floor(t * 4); if (box.dataset.k === String(k)) return; box.dataset.k = k;
  const t0 = Math.max(0, t - 4), t1 = t0 + 10; const ws = S().words.filter(w => w.t1 > t0 && w.t0 < t1); const segs = S().segs.filter(s => s.t1 > t0 && s.t0 < t1);
  const win = box.querySelector('[data-win]'); if (!win) return;
  win.innerHTML = `<div class="vlab">${V.fmt(t0)} – ${V.fmt(t1)}</div><div style="position:relative;height:40px;overflow:hidden;border-bottom:1px solid var(--rule)">${ws.map(w => `<span data-sel="${w.i}.${w.i}" style="position:absolute;left:${pctIn(w.t0, t0, t1)}%;top:${w.i % 2 ? 20 : 2}px;white-space:nowrap;cursor:pointer;font:${t >= w.t0 && t < w.t1 ? 700 : 400} ${wide ? 15 : 12}px var(--sans);color:${t >= w.t0 && t < w.t1 ? 'var(--red)' : 'var(--ink)'}">${esc(w.text)}</span>`).join('')}</div><div style="position:relative;height:${wide ? 80 : 46}px;margin-top:4px">${segs.map(s => { const a = pctIn(s.t0, t0, t1), b = pctIn(s.t1, t0, t1); return `<div style="position:absolute;left:${a}%;width:calc(${b - a}% - 1px);top:0;bottom:0">${segThumb(s, { style: '--w:100%;aspect-ratio:auto;height:100%;border-width:1px' })}</div>`; }).join('')}<span class="vhead" style="left:${pctIn(t, t0, t1)}%;top:-50px"></span></div>`;
}
R('204', 'Playhead Bind', 'The playhead bound to the text: the word being spoken, the shot on screen, and what comes next.', (box, v, o) => {
  box.innerHTML = `<div data-ph></div>`; box.dataset.k = ''; draw204(box, S().t, o.wide);
}, { tick: (box, v, t) => draw204(box, t, box.classList.contains('wide')) });
function draw204(box, t, wide) {
  const w = V.wordAt(t); const seg = V.segAt(t); const key = (w ? w.i : -1) + '|' + (seg ? seg.key : ''); if (box.dataset.k === key) { const bar = box.querySelector('[data-pr]'); if (bar && seg) bar.style.width = pctIn(t, seg.t0, seg.t1) + '%'; const lb = box.querySelector('[data-clock]'); if (lb) lb.textContent = V.fmt(t) + (S().playing ? ' · playing' : ' · paused'); return; } box.dataset.k = key;
  const i = S().segs.indexOf(seg); const nx = S().segs.slice(i + 1, i + 4); const ph = box.querySelector('[data-ph]'); if (!ph) return;
  const line = w ? S().words.filter(x => x.L === w.L) : [];
  ph.innerHTML = `<div style="text-align:center;margin-bottom:12px"><div class="vlab" data-clock>${V.fmt(t)}${S().playing ? ' · playing' : ' · paused'}</div><div style="font:900 ${wide ? 54 : 34}px/1 var(--sans);font-stretch:70%;text-transform:uppercase;color:var(--red);min-height:1em">${w ? esc(w.text) : '—'}</div><div class="vtext" style="font-size:${wide ? 15 : 13}px;margin-top:6px">${line.map(x => x === w ? `<b style="color:var(--red)">${esc(x.text)}</b>` : esc(x.text)).join(' ')}</div></div>
  <div style="display:flex;gap:${wide ? 16 : 8}px;align-items:flex-end;justify-content:center;flex-wrap:wrap"><div class="vcol"><div class="vlab">on screen</div>${seg ? segThumb(seg, { w: wide ? 300 : 160 }) : ''}<div style="width:${wide ? 300 : 160}px;height:4px;background:var(--box)"><i data-pr style="display:block;height:100%;background:var(--red);width:${seg ? pctIn(t, seg.t0, seg.t1) : 0}%"></i></div></div>${nx.map((s, k) => `<div class="vcol" style="opacity:${1 - k * 0.22}"><div class="vlab">next ${V.fmt0(s.t0)}</div>${segThumb(s, { w: wide ? 110 : 60 })}</div>`).join('')}</div>`;
}
R('205', 'Text to Timeline', 'The stanza’s lines dropped onto the poem’s 24-minute clock, each where it falls.', (box, v, o) => {
  const P = V.around('stanza'); const lines = V.unitsIn(P.a, P.b, 'line'); const f = S().films[S().words[P.a].film]; const t0 = f.container[0], t1 = f.container[1];
  box.innerHTML = `<div class="vrow" style="gap:6px;margin-bottom:${W(o, 40, 56)}px">${lines.map((u, i) => `<span class="vnode${isSel(u) ? ' sel' : ''}" data-sel="${u.a}.${u.b}" data-l="${i}" style="font-size:11.5px;max-width:${W(o, 150, 240)}px;text-align:left">${esc(u.text.slice(0, 70))}</span>`).join('')}</div><div class="vlab">${esc(f.n + ' ' + f.title)}</div><div style="position:relative;height:36px;background:var(--box);border-radius:2px">${f.stanzas.map(i => S().stanzas[i]).map(s => `<i style="position:absolute;top:0;bottom:0;left:${pctIn(s.t0, t0, t1)}%;width:${pctIn(s.t1, t0, t1) - pctIn(s.t0, t0, t1)}%;background:var(--faint);opacity:.5"></i>`).join('')}${lines.map((u, i) => `<i data-t="${i}" style="position:absolute;top:0;bottom:0;left:${pctIn(u.t0, t0, t1)}%;width:max(2px,${pctIn(u.t1, t0, t1) - pctIn(u.t0, t0, t1)}%);background:${isSel(u) ? 'var(--blue)' : 'var(--ink)'};opacity:.8"></i>`).join('')}</div><div class="vruler"><span style="left:0">${V.fmt0(t0)}</span><span style="left:88%">${V.fmt0(t1)}</span></div>`;
  wire(box, lines.map((u, i) => [box.querySelector(`[data-l="${i}"]`), box.querySelector(`[data-t="${i}"]`), { arrow: true, color: isSel(u) ? 'var(--blue)' : 'var(--faint)' }]));
});
R('206', 'Phrase Scrub', 'Drag along the bar to scrub the reading word by word; the frame and the word follow your finger.', (box, v, o) => {
  const L = V.around('line'); const ws = words(L); const span = L.t1 - L.t0 || 1;
  box.innerHTML = `<div style="text-align:center;margin-bottom:8px"><div data-fr style="max-width:${W(o, 260, 480)}px;margin:0 auto"></div></div><div style="display:flex;gap:2px;margin-bottom:6px">${ws.map(w => `<span data-wi="${w.i}" style="flex:${(w.t1 - w.t0) / span} 0 0;min-width:0;overflow:hidden;white-space:nowrap;text-overflow:clip;font:400 ${W(o, 11, 14)}px var(--sans);text-align:center">${esc(w.text)}</span>`).join('')}</div><div data-bar style="position:relative;height:34px;background:var(--box);border:1.5px solid var(--ink);border-radius:3px;cursor:ew-resize;touch-action:none"><div data-knob style="position:absolute;top:-4px;bottom:-4px;width:12px;margin-left:-6px;background:var(--blue);border-radius:3px"></div></div><div class="vruler"><span style="left:0">${V.fmt(L.t0)}</span><span style="left:85%">${V.fmt(L.t1)}</span></div>`;
  const bar = box.querySelector('[data-bar]'), knob = box.querySelector('[data-knob]'), fr = box.querySelector('[data-fr]');
  let lastSeg = null;
  const upd = t => { knob.style.left = pctIn(t, L.t0, L.t1) + '%'; box.querySelectorAll('[data-wi]').forEach(e => { const w = S().words[+e.dataset.wi]; e.style.color = t >= w.t0 && t < w.t1 ? 'var(--red)' : ''; e.style.fontWeight = t >= w.t0 && t < w.t1 ? 700 : 400; }); const sg = V.segAt(t); if (sg !== lastSeg) { lastSeg = sg; fr.innerHTML = sg ? segThumb(sg, { w: '100%' }) : ''; } };
  const at = e => { const r = bar.getBoundingClientRect(); return L.t0 + Math.max(0, Math.min(1, (e.clientX - r.left) / r.width)) * span; };
  let down = false;
  bar.addEventListener('pointerdown', e => { down = true; bar.setPointerCapture(e.pointerId); const t = at(e); V.seek(t); upd(t); });
  bar.addEventListener('pointermove', e => { if (!down) return; const t = at(e); V.seek(t); upd(t); });
  bar.addEventListener('pointerup', () => { down = false; });
  upd(Math.max(L.t0, Math.min(L.t1, S().t)));
});
R('207', 'Word Stepper', 'Step through the reading one word at a time; each step plays just that word.', (box, v, o) => {
  const w = S().words[sel().a]; const L = V.around('line'); const ws = words(L);
  box.innerHTML = `<div style="text-align:center"><div class="vtext" style="font-size:${W(o, 14, 17)}px;margin-bottom:14px">${ws.map(x => `<span data-sel="${x.i}.${x.i}" style="cursor:pointer;${x.i === w.i ? 'background:var(--blue);color:#fff;padding:0 3px;border-radius:2px' : ''}">${esc(x.text)}</span>`).join(' ')}</div><div class="vbar" style="justify-content:center">${[['⏮', 'first'], ['◀', 'prev'], ['▶', 'play'], ['▶▶', 'next'], ['⏭', 'last']].map(([s, k]) => `<button class="vbtn${k === 'play' ? ' on' : ''}" data-st="${k}" style="min-width:44px;font-size:15px">${s}</button>`).join('')}</div><div class="vnote" style="text-align:center">word ${w.i - L.a + 1} of ${ws.length} · ${(w.t1 - w.t0).toFixed(2)} s</div></div>`;
  box.querySelectorAll('[data-st]').forEach(b => b.onclick = () => { const k = b.dataset.st; let i = w.i; if (k === 'first') i = L.a; else if (k === 'prev') i = Math.max(0, w.i - 1); else if (k === 'next') i = Math.min(S().words.length - 1, w.i + 1); else if (k === 'last') i = L.b; V.setSel({ a: i, b: i }, { seek: false, scroll: true }); V.playSel(false); });
});
R('209', 'Elastic Spacing', 'The line set with the spaces between words stretched to the pauses between them.', (box, v, o) => {
  const P = V.around('stanza'); const lines = V.unitsIn(P.a, P.b, 'line');
  box.innerHTML = lines.map(u => { const ws = words(u); const span = u.t1 - u.t0 || 1; return `<div style="position:relative;height:${W(o, 30, 36)}px;border-bottom:1px dashed var(--rule);margin-bottom:6px">${ws.map(w => `<span data-sel="${w.i}.${w.i}" style="position:absolute;left:${pctIn(w.t0, u.t0, u.t1)}%;bottom:4px;cursor:pointer;white-space:nowrap;font:400 ${W(o, 11, 15)}px var(--sans);${w.i >= sel().a && w.i <= sel().b ? 'color:var(--blue);font-weight:600' : ''}">${esc(w.text)}</span>`).join('')}<small style="position:absolute;right:0;top:0;font:500 9px var(--mono);color:var(--dim)">${span.toFixed(1)} s</small></div>`; }).join('') + h.note('Words sit where they are spoken along each line; wide gaps are pauses.');
});
R('210', 'Loop Phrase', 'The words as a loop: set how many times, and play them round.', (box, v, o) => {
  const st = h.state('210', { n: 3 }); const u = V.rangeOf(sel().a, sel().b); const d = u.t1 - u.t0;
  box.innerHTML = `<div style="display:flex;justify-content:center"><div style="position:relative;width:${W(o, 260, 380)}px;aspect-ratio:1"><svg viewBox="0 0 100 100" style="position:absolute;inset:0"><circle cx="50" cy="50" r="40" fill="none" stroke="var(--blue)" stroke-width="2" stroke-dasharray="4 3"/><path d="M86 38 l4 8 l-9 -1" fill="none" stroke="var(--blue)" stroke-width="2"/></svg><div style="position:absolute;inset:22%;display:flex;align-items:center;justify-content:center;text-align:center;font:500 ${W(o, 13, 17)}px/1.3 var(--sans)">${esc(h.q(90))}</div></div></div><div class="vbar" style="justify-content:center"><button class="vbtn" data-n="-1">−</button><span style="font:600 14px var(--mono)">× ${st.n}</span><button class="vbtn" data-n="1">+</button><button class="vbtn on" data-go>⟲ loop ${(d * st.n).toFixed(1)} s</button><button class="vbtn" data-stop>■</button></div>`;
  box.querySelectorAll('[data-n]').forEach(b => b.onclick = () => { st.n = Math.max(1, Math.min(12, st.n + +b.dataset.n)); V.rerender(); });
  box.querySelector('[data-go]').onclick = () => { V.playSel(true); clearTimeout(st.tm); st.tm = setTimeout(() => { if (S().loop) document.getElementById('loopSel').click(); V.pause(); }, d * st.n * 1000 / (+document.getElementById('tempo').value || 1)); };
  box.querySelector('[data-stop]').onclick = () => { clearTimeout(st.tm); if (S().loop) document.getElementById('loopSel').click(); V.pause(); };
});
R('211', 'Nested Timeline', 'Timelines inside timelines: the poem, the passage, the stanza, the line.', (box, v, o) => {
  const s = sel(); const D = V.D.duration; const f = S().films[S().words[s.a].film]; const st = V.around('stanza'), ln = V.around('line');
  const lev = [['poem', 0, D], ['passage', f.container[0], f.container[1]], ['stanza', st.t0, st.t1], ['line', ln.t0, ln.t1]];
  box.innerHTML = lev.map(([k, a, b], i) => { const nx = lev[i + 1]; const segs = S().segs.filter(x => x.t1 > a && x.t0 < b); const thumbs = segs.length < 60; return `<div class="vlab" style="margin-top:${i ? 26 : 0}px">${k} · ${V.fmt0(a)}–${V.fmt0(b)}</div><div data-lv="${i}" style="position:relative;height:${W(o, 26, 34)}px;background:var(--box)">${thumbs ? segs.map(x => `<div style="position:absolute;top:0;bottom:0;left:${pctIn(x.t0, a, b)}%;width:calc(${pctIn(x.t1, a, b) - pctIn(x.t0, a, b)}% - 1px)">${segThumb(x, { style: '--w:100%;aspect-ratio:auto;height:100%;border-width:1px' })}</div>`).join('') : S().films.map(ff => `<i style="position:absolute;top:0;bottom:0;left:${pctIn(ff.container[0], a, b)}%;width:${pctIn(ff.container[1], a, b) - pctIn(ff.container[0], a, b)}%;background:${ff.world.accent || 'var(--faint)'};opacity:.6;border-right:1px solid var(--panel)"></i>`).join('')}${nx ? `<div data-z="${i}" class="vspan" style="top:0;bottom:0;left:${pctIn(nx[1], a, b)}%;width:max(2px,${pctIn(nx[2], a, b) - pctIn(nx[1], a, b)}%)"></div>` : ''}<span class="vhead" style="left:${pctIn(S().t, a, b)}%"></span></div>`; }).join('');
  const links = []; for (let i = 0; i < 3; i++) { const z = box.querySelector(`[data-z="${i}"]`), n = box.querySelector(`[data-lv="${i + 1}"]`); links.push([z, n, { dash: true, color: 'var(--blue)' }]); } wire(box, links);
});
R('212', 'Parallel Channels', 'Five channels on one clock over the stanza: your shots, then the suite, scenes, cineosis and drift cuts.', (box, v, o) => {
  const P = V.around('stanza'); const a = P.t0, b = P.t1;
  const row = (k, items) => `<div style="display:grid;grid-template-columns:${W(o, 60, 80)}px minmax(0,1fr);gap:8px;align-items:center;margin-bottom:4px"><span class="vlab" style="margin:0;${k === 'mine' ? 'color:var(--blue)' : ''}">${k}</span><div style="position:relative;height:${W(o, 30, 50)}px;background:var(--box)">${items}</div></div>`;
  const mine = S().binds.filter(x => x.t1 > a && x.t0 < b).map(x => `<div style="position:absolute;top:0;bottom:0;left:${pctIn(x.t0, a, b)}%;width:calc(${pctIn(x.t1, a, b) - pctIn(x.t0, a, b)}% - 1px)">${h.ts(V.shot(x.shot.id) || x.shot, { in: x.in, cls: 'mine', grade: false, style: '--w:100%;aspect-ratio:auto;height:100%' })}</div>`).join('');
  box.innerHTML = row('mine', mine) + cutsN.map(c => row(c, (V.D.cuts[c] || []).filter(p => p.t1 > a && p.t0 < b).map(p => `<div style="position:absolute;top:0;bottom:0;left:${pctIn(p.t0, a, b)}%;width:calc(${pctIn(p.t1, a, b) - pctIn(p.t0, a, b)}% - 1px)">${h.ts(V.shot(p.id) || p, { in: p.in + Math.max(0, a - p.t0), grade: false, style: '--w:100%;aspect-ratio:auto;height:100%;border-width:1px' })}</div>`).join(''))).join('') + `<div style="display:grid;grid-template-columns:${W(o, 60, 80)}px 1fr;gap:8px"><span></span><div class="vruler"><span style="left:0">${V.fmt(a)}</span><span style="left:85%">${V.fmt(b)}</span></div></div>`;
});
R('213', 'Branch on Word', 'From the word you hold the film can go four ways: the next shots in each cut.', (box, v, o) => {
  const w = S().words[sel().a]; const t = w.t0 + 0.01;
  box.innerHTML = `<div style="display:grid;grid-template-columns:${W(o, '80px', '140px')} minmax(0,1fr);gap:${W(o, 12, 30)}px;align-items:center"><div style="text-align:center"><span class="vnode sel" data-root style="font-size:${W(o, 13, 17)}px">${esc(w.text)}</span><div class="vnote" style="margin:4px 0 0">${V.fmt(w.t0)}</div></div><div>${cutsN.map(c => { const l = (V.D.cuts[c] || []).filter(p => p.t1 > t).slice(0, W(o, 3, 5)); return `<div style="display:flex;gap:4px;align-items:center;margin:6px 0"><span class="vlab" style="margin:0;width:62px" data-br="${c}">${c}</span>${l.map((p, k) => h.ts(V.shot(p.id) || p, { w: W(o, 54 - k * 6, 96 - k * 10), in: p.in, grade: false })).join('<span style="color:var(--faint)">→</span>')}</div>`; }).join('')}</div></div>`;
  const r = box.querySelector('[data-root]'); wire(box, cutsN.map(c => [r, box.querySelector(`[data-br="${c}"]`), { mode: 'h', color: 'var(--blue)' }]));
});
R('215', 'Staggered Start', 'The stanza’s lines staggered by when they start: a cascade of the reading.', (box, v, o) => {
  const P = V.around('stanza'); const lines = V.unitsIn(P.a, P.b, 'line'); const a = P.t0, b = P.t1;
  box.innerHTML = lines.map(u => { const seg = V.segAt(u.t0 + 0.05); return `<div style="position:relative;height:${W(o, 34, 44)}px;margin-bottom:3px"><div data-sel="${u.a}.${u.b}" style="position:absolute;left:${pctIn(u.t0, a, b)}%;width:max(60px,${pctIn(u.t1, a, b) - pctIn(u.t0, a, b)}%);top:0;bottom:0;display:flex;gap:6px;align-items:center;border:1.5px solid ${isSel(u) ? 'var(--blue)' : 'var(--ink)'};background:${isSel(u) ? 'var(--blue-soft)' : 'var(--panel)'};padding:2px;cursor:pointer;overflow:hidden">${seg ? segThumb(seg, { w: W(o, 36, 52) }) : ''}<span style="font:400 ${W(o, 10.5, 12.5)}px/1.2 var(--sans);white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(u.text)}</span></div></div>`; }).join('') + `<div class="vruler"><span style="left:0">${V.fmt(a)}</span><span style="left:85%">${V.fmt(b)}</span></div>`;
});
R('217', 'Tempo Control', 'Slow the reading down or speed it up, from tortoise to hare; the words keep their shots.', (box, v, o) => {
  const tp = document.getElementById('tempo'); const cur = +tp.value; const d = sel().t1 - sel().t0;
  box.innerHTML = `<div style="max-width:${W(o, 320, 560)}px;margin:0 auto;text-align:center"><div style="display:flex;align-items:center;gap:12px;font-size:26px"><span title="slow">🐢</span><input type="range" min="0" max="4" step="1" value="${[0.5, 0.75, 1, 1.25, 1.5].indexOf(cur)}" style="flex:1" data-tp><span title="fast">🐇</span></div><div style="font:700 28px var(--mono);margin:8px 0">${cur}×</div><div class="vnote" style="text-align:center">“${esc(h.q(60))}” lasts ${(d / cur).toFixed(1)} s at this tempo (${d.toFixed(1)} s at 1×).</div><button class="vbtn on" data-pl>▷ hear it</button></div>`;
  box.querySelector('[data-tp]').oninput = e => { tp.value = [0.5, 0.75, 1, 1.25, 1.5][+e.target.value]; tp.dispatchEvent(new Event('change')); V.rerender(); };
  box.querySelector('[data-pl]').onclick = () => V.playSel(false);
});
R('221', 'Keyframe Text', 'The words as keyframes on the clock: diamonds you can jump between.', (box, v, o) => {
  const L = V.around('line'); const ws = words(L);
  box.innerHTML = `<div style="position:relative;height:${W(o, 90, 110)}px;margin:0 12px">${ws.map((w, i) => `<div data-sel="${w.i}.${w.i}" data-seek="${w.t0}" style="position:absolute;left:${pctIn(w.t0, L.t0, L.t1)}%;top:${i % 2 ? 50 : 8}px;transform:translateX(-50%);cursor:pointer;text-align:center"><span style="display:block;font:400 ${W(o, 11, 13)}px var(--sans);white-space:nowrap;${w.i >= sel().a && w.i <= sel().b ? 'color:var(--blue);font-weight:600' : ''}">${esc(w.text)}</span></div>`).join('')}<div style="position:absolute;left:0;right:0;bottom:12px;border-top:1.5px solid var(--ink)"></div>${ws.map(w => `<i data-seek="${w.t0}" data-sel="${w.i}.${w.i}" style="position:absolute;left:${pctIn(w.t0, L.t0, L.t1)}%;bottom:7px;width:10px;height:10px;transform:translateX(-50%) rotate(45deg);background:${w.i >= sel().a && w.i <= sel().b ? 'var(--blue)' : 'var(--panel)'};border:1.5px solid var(--blue);cursor:pointer"></i>`).join('')}</div><div class="vruler" style="margin:0 12px"><span style="left:0">${V.fmt(L.t0)}</span><span style="left:85%">${V.fmt(L.t1)}</span></div>`;
});
R('224', 'Segment Grid', 'The passage cut into its clips, laid out as a grid in time order with their timecodes.', (box, v, o) => {
  const f = S().films[S().words[sel().a].film]; const segs = S().segs.filter(s => s.t1 > f.container[0] && s.t0 < f.container[1]);
  box.innerHTML = `<div class="vlab">${esc(f.n + ' ' + f.title)} · ${segs.length} clips</div><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(${W(o, 70, 104)}px,1fr));gap:6px">${segs.map(s => `<div style="${s.t1 > sel().t0 && s.t0 < sel().t1 ? 'outline:2px solid var(--blue);outline-offset:2px' : ''}">${segThumb(s, { w: '100%' })}<small data-seek="${s.t0}" style="display:block;cursor:pointer;font:500 9.5px var(--mono);color:${s.kind === 'mine' ? 'var(--blue)' : 'var(--dim)'};margin-top:2px">${V.fmt(s.t0)} · ${(s.t1 - s.t0).toFixed(1)}s</small></div>`).join('')}</div>`;
});
R('225', 'Text as Markers', 'Each line a marker pinned on the passage’s clock.', (box, v, o) => {
  const f = S().films[S().words[sel().a].film]; const a = f.container[0], b = f.container[1]; const lines = V.unitsIn(S().stanzas[f.stanzas[0]].a, S().stanzas[f.stanzas[f.stanzas.length - 1]].b, 'line');
  box.innerHTML = `<div style="position:relative;height:${W(o, 190, 210)}px;margin:0 8px">${lines.map((u, i) => `<div style="position:absolute;left:${pctIn(u.t0, a, b)}%;bottom:14px;height:${24 + (i % 6) * W(o, 26, 30)}px;border-left:1.5px solid ${isSel(u) ? 'var(--blue)' : 'var(--ink)'}"><span data-sel="${u.a}.${u.b}" style="position:absolute;top:-6px;left:-5px;width:10px;height:10px;border-radius:50%;background:${isSel(u) ? 'var(--blue)' : 'var(--panel)'};border:1.5px solid ${isSel(u) ? 'var(--blue)' : 'var(--ink)'};cursor:pointer"></span>${o.wide || isSel(u) ? `<span data-sel="${u.a}.${u.b}" style="position:absolute;top:-8px;${pctIn(u.t0, a, b) > 65 ? 'right:8px' : 'left:8px'};white-space:nowrap;font:400 10.5px var(--sans);cursor:pointer;max-width:200px;overflow:hidden;text-overflow:ellipsis;background:var(--paper)">${esc(u.text.slice(0, 40))}</span>` : ''}</div>`).join('')}<div style="position:absolute;left:0;right:0;bottom:12px;border-top:2px solid var(--ink)"></div></div><div class="vruler" style="margin:0 8px"><span style="left:0">${V.fmt0(a)}</span><span style="left:88%">${V.fmt0(b)}</span></div>`;
});
R('228', 'Split on Pause', 'The stanza split wherever the reading pauses: at every stop, colon and dash.', (box, v, o) => {
  const P = V.around('stanza'); const ph = V.unitsIn(P.a, P.b, 'phrase');
  box.innerHTML = `<div class="vrow" style="align-items:center;gap:6px">${ph.map((u, i) => `${i ? '<span style="font:900 18px var(--sans);color:var(--blue)">‖</span>' : ''}<span class="vnode${isSel(u) ? ' sel' : ''}" data-sel="${u.a}.${u.b}" style="text-align:left">${esc(u.text)}<small>${(u.t1 - u.t0).toFixed(1)}s</small></span>`).join('')}</div>${h.note(`${ph.length} pieces; each can be gripped and coupled on its own.`)}`;
});
R('231', 'Time Remap', 'The reading as a curve: words along, time up. Steep stretches are slow words; flat ones are quick.', (box, v, o) => {
  const P = V.around('stanza'); const ws = words(P); const n = ws.length; const T = P.t1 - P.t0 || 1;
  const pts = ws.map((w, i) => [4 + i / Math.max(1, n - 1) * 92, 94 - (w.t0 - P.t0) / T * 88]);
  box.innerHTML = `<div style="position:relative;aspect-ratio:${W(o, '1.3', '2.2')};max-width:900px;margin:0 auto"><svg viewBox="0 0 100 100" preserveAspectRatio="none" style="position:absolute;inset:0;width:100%;height:100%;overflow:visible"><path d="M4 6 V94 H96" fill="none" stroke="var(--ink)" stroke-width=".4" vector-effect="non-scaling-stroke"/><path d="M4 94 L96 6" stroke="var(--faint)" stroke-dasharray="2 2" fill="none" vector-effect="non-scaling-stroke"/><polyline points="${pts.map(p => p.join(',')).join(' ')}" fill="none" stroke="var(--blue)" stroke-width="2" vector-effect="non-scaling-stroke"/></svg>${ws.map((w, i) => `<span data-sel="${w.i}.${w.i}" title="${esc(w.text)} · ${V.fmt(w.t0)}" style="position:absolute;left:${pts[i][0]}%;top:${pts[i][1]}%;width:${w.i >= sel().a && w.i <= sel().b ? 10 : 6}px;height:${w.i >= sel().a && w.i <= sel().b ? 10 : 6}px;border-radius:50%;background:${w.i >= sel().a && w.i <= sel().b ? 'var(--blue)' : 'var(--panel)'};border:1.5px solid var(--blue);transform:translate(-50%,-50%);cursor:pointer"></span>`).join('')}<span class="vaxis" style="left:5%;top:0">time ↑ ${T.toFixed(0)} s</span><span class="vaxis" style="right:0;bottom:-2px">words → ${n}</span></div>`;
});
R('234', 'Variable Speed', 'How fast each line is read, in words a second: where the voice hurries and where it lingers.', (box, v, o) => {
  const f = S().films[S().words[sel().a].film]; const lines = V.unitsIn(S().stanzas[f.stanzas[0]].a, S().stanzas[f.stanzas[f.stanzas.length - 1]].b, 'line');
  const rate = u => (u.b - u.a + 1) / Math.max(0.3, u.t1 - u.t0); const max = Math.max(...lines.map(rate));
  box.innerHTML = `<div class="vlab">${esc(f.n + ' ' + f.title)} · words per second</div><div style="display:flex;align-items:flex-end;gap:2px;height:${W(o, 140, 200)}px;border-bottom:1.5px solid var(--ink)">${lines.map(u => `<div data-sel="${u.a}.${u.b}" title="${esc(u.text)}\n${rate(u).toFixed(2)} words/s" style="flex:1;min-width:3px;height:${rate(u) / max * 100}%;background:${isSel(u) ? 'var(--blue)' : 'var(--faint)'};cursor:pointer"></div>`).join('')}</div><div class="vnote" style="margin-top:6px">${lines.length} lines; the held line reads at <b>${rate(V.around('line')).toFixed(2)}</b> words a second.</div>`;
});
R('238', 'Chapter Mark', 'The fourteen passages as chapter flags on the 24-minute clock.', (box, v, o) => {
  const D = V.D.duration; const cur = S().words[sel().a].film;
  box.innerHTML = `<div style="position:relative;height:${W(o, 150, 150)}px">${S().films.map((f, i) => { const p = V.cutAt('suite', f.poem[0] + 1); const s0 = S().stanzas[f.stanzas[0]]; return `<div style="position:absolute;left:${f.container[0] / D * 100}%;bottom:0;height:${40 + (i % 3) * 34}px;border-left:1.5px solid ${i === cur ? 'var(--blue)' : 'var(--ink)'}"><div data-sel="${s0.a}.${S().stanzas[f.stanzas[f.stanzas.length - 1]].b}" style="position:absolute;top:0;${f.container[0] / D > 0.6 ? 'right:0' : 'left:0'};display:flex;gap:4px;align-items:center;background:${i === cur ? 'var(--blue)' : 'var(--ink)'};color:#fff;padding:1px 5px 1px 1px;font:600 9.5px var(--sans);white-space:nowrap;cursor:pointer">${o.wide && p ? `<i style="width:28px;height:20px;background:url('${esc((V.shot(p.id) || p).thumb)}') center/cover"></i>` : ''}${f.n}${o.wide || i === cur ? ' ' + esc(f.title.slice(0, 22)) : ''}</div></div>`; }).join('')}<span class="vhead" style="left:${S().t / D * 100}%"></span></div><div class="vruler">${[0, 5, 10, 15, 20].map(m => `<span style="left:${m * 60 / D * 100}%">${m}:00</span>`).join('')}</div>`;
});
R('239', 'Alternate Takes', 'The same words, four takes: what each cut put there. Use a take to couple it.', (box, v, o) => {
  const u = V.rangeOf(sel().a, sel().b);
  box.innerHTML = `<div style="display:grid;grid-template-columns:repeat(${W(o, 2, 4)},minmax(0,1fr));gap:12px">${cutsN.map((c, i) => { const p = V.cutAt(c, u.t0 + 0.01); const s = p && (V.shot(p.id) || p); return `<div class="vframe"><div class="vlab">take ${'ABCD'[i]} · ${c}</div>${s ? h.ts(s, { w: '100%', in: p.in + Math.max(0, u.t0 - p.t0) }) : ''}<div class="vcap" style="--w:100%">${s ? esc(s.title) : ''}<small>${s && s.year || ''}</small></div>${s ? `<button class="vbtn" data-use="${i}" style="margin-top:6px">use take ${'ABCD'[i]}</button>` : ''}</div>`; }).join('')}</div>`;
  box.querySelectorAll('[data-use]').forEach(b => b.onclick = () => { const p = V.cutAt(cutsN[+b.dataset.use], u.t0 + 0.01); V.coupleTo(V.shot(p.id) || p, u.a, u.b, p.in + Math.max(0, u.t0 - p.t0)); });
});
R('241', 'Grid to Sequence', 'Pick shots from the grid in the order you want; they become a sequence spread across the words.', (box, v, o) => {
  const st = h.state('241', { ids: [] }); const u = V.rangeOf(sel().a, sel().b); const l = h.top(o, 9, 16);
  st.ids = st.ids.filter(id => l.some(r => r.s.id === id));
  box.innerHTML = `<div style="display:flex;gap:${W(o, 12, 30)}px;align-items:center;flex-wrap:wrap;justify-content:center"><div style="display:grid;grid-template-columns:repeat(${W(o, 3, 4)},${W(o, 56, 80)}px);gap:4px">${l.map(r => { const k = st.ids.indexOf(r.s.id); return `<span data-pk="${esc(r.s.id)}" style="position:relative;cursor:pointer">${h.t(r, { w: W(o, 56, 80), grade: false, label: k >= 0 ? String(k + 1) : '' }).replace('data-id=', 'data-gid=')}${k >= 0 ? '<i style="position:absolute;inset:0;border:3px solid var(--blue);pointer-events:none"></i>' : ''}</span>`; }).join('')}</div><span style="font-size:26px">→</span><div><div class="vrow nw" style="gap:3px">${st.ids.map(id => h.ts(V.shot(id), { w: W(o, 50, 70), grade: false })).join('') || '<span class="vnote">pick shots in order</span>'}</div><button class="vbtn on" data-seq style="margin-top:8px" ${st.ids.length ? '' : 'disabled'}>sequence ${st.ids.length} over “${esc(h.q(30))}”</button></div></div>`;
  box.querySelectorAll('[data-pk]').forEach(b => b.onclick = () => { const id = b.dataset.pk; st.ids = st.ids.includes(id) ? st.ids.filter(x => x !== id) : st.ids.concat(id); V.rerender(); });
  box.querySelector('[data-seq]').onclick = () => { const n = Math.min(st.ids.length, u.b - u.a + 1); const per = (u.b - u.a + 1) / n; for (let k = 0; k < n; k++) { const a = u.a + Math.round(k * per), b = u.a + Math.round((k + 1) * per) - 1; V.coupleTo(V.shot(st.ids[k]), a, Math.max(a, b)); } st.ids = []; V.setSel({ a: u.a, b: u.b }); };
}, { needs: 'shots' });
R('242', 'Radial Play', 'The passage as a clock face of its clips; the hand is the playhead.', (box, v, o) => {
  const f = S().films[S().words[sel().a].film]; const a = f.container[0], b = f.container[1]; const segs = S().segs.filter(s => s.t1 > a && s.t0 < b).slice(0, 40); const w = W(o, 34, 60);
  let html = h.stage('1', W(o, '100%', '640px'));
  segs.forEach(s => { const mid = (Math.max(a, s.t0) + Math.min(b, s.t1)) / 2; const [x, y] = h.polar(40, -90 + (mid - a) / (b - a) * 360); html += h.at(x, y, segThumb(s, { w })); });
  html += `<div data-hand style="position:absolute;left:50%;top:50%;width:2px;height:30%;background:var(--red);transform-origin:50% 0;z-index:5"></div>` + h.at(50, 50, `<button class="vbtn on" data-pp style="border-radius:50%;width:${W(o, 56, 80)}px;height:${W(o, 56, 80)}px;font-size:22px">${S().playing ? '❚❚' : '▶'}</button><div class="vnote" style="text-align:center;margin:4px 0 0">${f.n}</div>`, 'z-index:6');
  box.innerHTML = html + '</div>';
  box.querySelector('[data-pp]').onclick = () => { S().playing ? V.pause() : (V.seek(Math.max(a, Math.min(b, S().t))), V.play()); setTimeout(V.rerender, 300); };
  box.dataset.a = a; box.dataset.b = b; hand242(box, S().t);
}, { tick: (box, v, t) => hand242(box, t) });
function hand242(box, t) { const hd = box.querySelector('[data-hand]'); if (!hd) return; const a = +box.dataset.a, b = +box.dataset.b; const ang = (Math.max(a, Math.min(b, t)) - a) / (b - a) * 360; hd.style.transform = `rotate(${ang + 180}deg)`; }
R('243', 'Spiral Sequence', 'The whole film wound into a spiral from the first clip at the centre; the one playing glows.', (box, v, o) => {
  const segs = S().segs.filter(s => s.kind !== 'text'); const n = segs.length; const w = W(o, 14, 26);
  let html = h.stage('1', W(o, '100%', '720px'));
  segs.forEach((s, i) => { const t = i / n; const ang = t * Math.PI * 2 * 5.5; const r = 4 + t * 44; html += h.at(50 + r * Math.cos(ang), 50 + r * Math.sin(ang), segThumb(s, { w: Math.round(w * (0.6 + t * 0.8)) }), `" data-sg="${S().segs.indexOf(s)}`); });
  box.innerHTML = html + '</div>'; box.dataset.cur = ''; glow243(box, S().t);
}, { tick: (box, v, t) => glow243(box, t) });
function glow243(box, t) { const s = V.segAt(t); const i = String(S().segs.indexOf(s)); if (box.dataset.cur === i) return; const old = box.querySelector(`[data-sg="${box.dataset.cur}"]`); if (old) { old.style.zIndex = ''; old.firstElementChild.style.boxShadow = ''; } box.dataset.cur = i; const e = box.querySelector(`[data-sg="${i}"]`); if (e) { e.style.zIndex = 50; e.firstElementChild.style.boxShadow = '0 0 0 3px var(--red)'; } }
R('246', 'Timeline Fold', 'The stanza you hold laid flat; the stanzas before and after folded away in perspective.', (box, v, o) => {
  const P = V.around('stanza'); const f = S().films[S().words[P.a].film]; const sts = f.stanzas.map(i => S().stanzas[i]); const ci = sts.findIndex(s => s.a <= P.a && s.b >= P.a);
  const panel = (s, d) => { const segs = S().segs.filter(x => x.t1 > s.t0 && x.t0 < s.t1).slice(0, 6); return `<div data-sel="${s.a}.${s.b}" style="flex:0 0 ${d ? W(o, 70, 150) : W(o, 180, 380)}px;cursor:pointer;transform:${d ? `rotateY(${d < 0 ? 55 : -55}deg)` : 'none'};transform-origin:${d < 0 ? 'right' : 'left'};border:1.5px solid ${d ? 'var(--ink)' : 'var(--blue)'};background:${d ? 'var(--panel)' : 'var(--blue-soft)'};padding:6px;opacity:${d ? 0.75 : 1}"><div class="vlab" style="margin-bottom:4px">${V.fmt0(s.t0)}</div><div class="vrow" style="gap:2px">${segs.map(x => segThumb(x, { w: d ? W(o, 26, 40) : W(o, 50, 80) })).join('')}</div>${d ? '' : `<div class="vtext" style="font-size:12px;margin-top:6px">${esc(s.text.slice(0, 160))}</div>`}</div>`; };
  const L = sts.slice(Math.max(0, ci - 2), ci), Rr = sts.slice(ci + 1, ci + 3);
  box.innerHTML = `<div class="v3d" style="display:flex;justify-content:center;align-items:center;gap:0;perspective:700px;padding:10px 0">${L.map(s => panel(s, -1)).join('')}${panel(sts[ci], 0)}${Rr.map(s => panel(s, 1)).join('')}</div>`;
});
R('248', 'Scene Flow', 'The passage’s beats as a flow, each with the shot its review chose.', (box, v, o) => {
  const f = S().films[S().words[sel().a].film]; const bs = V.D.beats.filter(b => b.start < f.container[1] && b.end > f.container[0]); const cur = V.beatsIn(sel().t0, sel().t1).map(b => b.id);
  box.innerHTML = `<div class="vrow" style="gap:${W(o, 16, 34)}px;row-gap:26px;justify-content:center">${bs.map(b => { const c = (b.candidates || []).find(x => x.id === b.selected) || (b.candidates || [])[0]; const s = c && (V.shot(c.id) || c); const w0 = S().words.find(w => w.t0 >= b.start); return `<div class="vcol" data-bn style="width:${W(o, 92, 130)}px;gap:3px">${s ? h.ts(s, { w: W(o, 92, 130), cls: cur.includes(b.id) ? 'mine' : '' }) : ''}<span ${w0 ? `data-seek="${b.start}"` : ''} style="cursor:pointer;font:600 10.5px/1.2 var(--sans);text-align:center;${cur.includes(b.id) ? 'color:var(--blue)' : ''}">${b.id} · ${esc(b.title)}</span><small style="color:var(--dim);font-size:9.5px">${esc(b.mode)}</small></div>`; }).join('')}</div>`;
  const ns = [...box.querySelectorAll('[data-bn]')]; h.arrows(box, ns.slice(1).map((n, i) => [ns[i], n]), { mode: 'h', dash: '3 3' });
});
R('250', 'Build Film', 'All the lines of the passage, each with its shot, gathered into the film.', (box, v, o) => {
  const f = S().films[S().words[sel().a].film]; const lines = V.unitsIn(S().stanzas[f.stanzas[0]].a, S().stanzas[f.stanzas[f.stanzas.length - 1]].b, 'line').slice(0, W(o, 8, 16));
  box.innerHTML = `<div style="display:flex;gap:${W(o, 12, 30)}px;align-items:center;justify-content:center;flex-wrap:wrap"><div>${lines.map(u => { const seg = V.segAt(u.t0 + 0.05); return `<div data-sel="${u.a}.${u.b}" style="display:flex;gap:6px;align-items:center;margin:2px 0;cursor:pointer;max-width:${W(o, 240, 420)}px">${seg ? segThumb(seg, { w: W(o, 30, 40) }) : ''}<span style="font:400 11px/1.2 var(--sans);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;${isSel(u) ? 'color:var(--blue)' : ''}">${esc(u.text)}</span></div>`; }).join('')}</div><span style="font-size:26px" data-arr>→</span><div style="text-align:center"><button class="vbtn on" data-play style="font-size:30px;padding:${W(o, 16, 26)}px ${W(o, 22, 34)}px;border-width:2px">▶</button><div class="vnote" style="text-align:center;margin-top:4px">${esc(f.n + ' ' + f.title)}</div></div></div>`;
  box.querySelector('[data-play]').onclick = () => { V.seek(f.container[0]); S().stopAt = null; V.play(); };
});
})();
