import {copy,duration,switches,joins,transform,shuffledStats,makeItems,edl,validate} from './model.mjs';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={autonomous:'Autonomous shot',parallel:'Parallel syntagma',alternate:'Alternate syntagma',scene:'Scene',bracket:'Bracket syntagma',ordinary:'Ordinary sequence'};
const stages=['find','bond','cut','test'];let D,p,items=[],selected=0,history=[],stage='find',sequence=[],index=0,epoch=0,transition=false,wanted=false,seed=17,blind=Math.random()<.5,revealed=false,activeMode='ORIGINAL',paletteSign=null,displayList=[],lastActive='';
const v=$('#film');const params=new URLSearchParams(location.search);if(params.has('source')||params.has('first'))location.replace('syntagm-bench.html'+location.search);
const time=t=>`${Math.floor(Math.max(0,t)/60)}:${(Math.max(0,t)%60).toFixed(1).padStart(4,'0')}`;
function say(s){$('#status').textContent=s}
const example=id=>D.examples.find(x=>x.id===id),sign=id=>D.signs.find(x=>x.n===id);
function canonical(){return makeItems(p)}
function changed(){return JSON.stringify(items.map(x=>[x.uid,x.example,x.in,x.out,x.sign]))!==JSON.stringify(canonical().map(x=>[x.uid,x.example,x.in,x.out,x.sign]))}
function stageTo(s){if(s==='bond'&&D&&items.length){stop();render();loadAt(items,selected,false,changed()?'YOUR CUT':'ORIGINAL')}stage=s;for(const x of stages)$('#'+x).hidden=x!==s;document.querySelectorAll('[data-stage]').forEach(b=>{b.classList.toggle('active',b.dataset.stage===s);b.setAttribute('aria-pressed',b.dataset.stage===s)});if(s==='test')renderTest()}
function persist(){try{localStorage.setItem('cineosis.operative.'+p.id,JSON.stringify({format:'cineosis-operative/1',base:p.id,items}));}catch{say('Storage unavailable. Export your cut to keep it.')}}
function renderFormula(list=items){displayList=list;const baseline=new Set(joins(canonical()).map(x=>x.key));$('#nodes').innerHTML=list.map((x,i)=>{let s=sign(x.sign);return `${i?`<span class="join ${baseline.has(list[i-1].uid+'>'+x.uid)?'':'changed'}" data-join="${i}" tabindex="0" role="button" aria-label="Play cut ${i}">${list[i-1].strand===x.strand?'—':'↔'}</span>`:''}<button class="node ${i===selected?'selected':''}" data-node="${i}" style="--strand:var(--${['A','B','C'].includes(x.strand)?x.strand.toLowerCase():'a'})" aria-label="Play ${esc(x.label)}"><b>${esc(x.strand)}${i+1} <span>${esc(s.symbol)}</span></b><small>${esc(x.label)}</small></button>`}).join('');
}
function render(){renderFormula(); $('#formulaName').textContent=changed()?'YOUR CUT · READING UNDER TEST':'ORIGINAL · STRANDS + PROPOSED SIGNS';const x=items[selected];$('#selection').textContent=`${selected+1}. ${x.label}`;$('#blockEvidence').textContent=`${sign(x.sign).symbol} · ${sign(x.sign).name}: ${x.signEvidence}`;let b=example(x.example).blocks.find(b=>b.id===x.id);$('#length').max=b.end-(example(x.example).start+x.in);$('#length').value=x.out-x.in;$('#lengthValue').textContent=(x.out-x.in).toFixed(1)+'s';$('#remove').disabled=items.length===1;$('#duplicate').disabled=items.length>=64;$('#undo').disabled=!history.length;$('#left').disabled=selected===0;$('#right').disabled=selected===items.length-1;$('#cutSummary').textContent=`${items.length} blocks · ${duration(items).toFixed(1)} seconds · ${switches(items)} strand changes. ${changed()?'Your variant is ready to play.':'The original source order is loaded.'}`;renderTest();}
function renderTest(){const a=canonical(),s=shuffledStats(a),orig=new Set(joins(a).map(x=>x.key)),newJoins=joins(items).filter(x=>!orig.has(x.key));$('#question').textContent=p.question;$('#suggested').textContent={group:'Group the strands',reverse:'Reverse the order',halve:'Halve the duration'}[p.operation];$('#metrics').innerHTML=`<span><b>${switches(a)}</b>original switches</span><span><b>${switches(items)}</b>your cut</span><span><b>${s.mean.toFixed(1)}</b>shuffle mean <small>(${s.min}–${s.max})</small></span>`;$('#metrics').title='499 seeded shuffles of the original blocks. Same durations and inventory. Descriptive control, not evidence of meaning.';$('#differences').innerHTML=`<span>${newJoins.length} new joins ·</span>`+newJoins.map(j=>`<button data-diff="${items.indexOf(j.right)}">${esc(j.left.strand)} → ${esc(j.right.strand)} · ${esc(j.right.label)}</button>`).join('')+(newJoins.length?'':'<span>Change the order to compare its joins.</span>');$('#compareA').textContent=revealed?`A · ${blind?'your cut':'original'}`:'Play A';$('#compareB').textContent=revealed?`B · ${blind?'original':'your cut'}`:'Play B';$('#reveal').textContent=revealed?'Hide identities':'Reveal A / B';}
function commit(next,message){stop();history.push(copy(items));if(history.length>30)history.shift();items=next;selected=Math.min(selected,items.length-1);render();persist();loadAt(items,selected,false,'YOUR CUT');say(message+' Original remains available.');}
function stop(){wanted=false;epoch++;transition=false;v.pause();$('#play').textContent='▶ Play';$('#bigPlay').hidden=false;}
function waitFor(event,token){return new Promise((resolve,reject)=>{const t=setTimeout(()=>{cleanup();reject(Error('Media did not become ready.'))},15000);const done=()=>{cleanup();resolve(token===epoch)};const fail=()=>{cleanup();reject(Error('Media could not be decoded.'))};function cleanup(){clearTimeout(t);v.removeEventListener(event,done);v.removeEventListener('error',fail)}v.addEventListener(event,done,{once:true});v.addEventListener('error',fail,{once:true});})}
async function loadAt(list,i,play,mode,start){const token=++epoch;transition=true;wanted=play;sequence=copy(list);index=i;activeMode=mode;renderFormula(sequence);$('#formulaName').textContent=mode==='ORIGINAL'?'ORIGINAL · STRANDS + PROPOSED SIGNS':mode==='A'||mode==='B'?mode+' · PLAYING STRUCTURE':'YOUR CUT · READING UNDER TEST';$('#version').textContent=mode;const x=sequence[index],ex=example(x.example),src=D.sources[ex.source];$('#filmSource').textContent=`${src.title} · ${src.year}`;$('#external').href=src.url;$('#failure').hidden=true;$('#shotLabel').textContent=x.label;$('#bigPlay').hidden=play;
 try{const url=new URL(ex.media,location.href).href;let t=start??x.in;if(v.src!==url){v.pause();v.poster=ex.poster;const ready=waitFor('loadedmetadata',token);v.src=url;v.load();await ready;}if(token!==epoch)return;if(Math.abs(v.currentTime-t)>.045){const ready=waitFor('seeked',token);v.currentTime=t;await ready;}if(token!==epoch)return;transition=false;syncActive();if(play){await v.play();if(token!==epoch)return;$('#play').textContent='Ⅱ Pause';}else{$('#play').textContent='▶ Play';} }catch(e){if(token!==epoch)return;transition=false;wanted=false;$('#failure').hidden=false;$('#bigPlay').hidden=true;say(e.message+' Use Retry or open the source.');}}
function syncActive(){const x=sequence[index];if(!x)return;let before=sequence.slice(0,index).reduce((t,x)=>t+x.out-x.in,0);$('#scrub').max=duration(sequence);$('#scrub').value=before+Math.min(x.out-x.in,Math.max(0,v.currentTime-x.in));$('#elapsed').textContent=`${time(+$('#scrub').value)} / ${time(duration(sequence))}`;$('#clock').textContent='SOURCE '+time(example(x.example).start+v.currentTime);$('#shotLabel').textContent=x.label;document.querySelectorAll('.node').forEach(n=>{const it=displayList[+n.dataset.node],active=it.uid===x.uid&&it.example===x.example;n.classList.toggle('playing',active);if(active&&lastActive!==x.uid){n.scrollIntoView({block:'nearest',inline:'center'});}n.style.setProperty('--progress',active?Math.max(0,Math.min(1,(v.currentTime-x.in)/(x.out-x.in))):0)});lastActive=x.uid;const left=sequence[index-1];const ex=example(x.example);const rel=left&&ex.relations.find(r=>r.left===left.id&&r.right===x.id&&left.example===x.example);$('#cutRelation').textContent=!left?'Opening block: '+x.label:rel?`${left.strand} → ${x.strand} · ${rel.kind}`:`${left.strand} → ${x.strand} · new join; original relation does not transfer automatically`;}
function tick(){if(sequence.length&&!transition){syncActive();let x=sequence[index];if(wanted&&v.currentTime>=x.out-.025){if(index<sequence.length-1){let next=sequence[index+1];if(next.example===x.example&&Math.abs(next.in-x.out)<.045){index++;syncActive();}else loadAt(sequence,index+1,true,activeMode);}else{wanted=false;v.pause();$('#play').textContent='↺ Replay';$('#bigPlay').hidden=false;}}}requestAnimationFrame(tick)}
function playItems(list,mode){loadAt(list,0,true,mode)}
function playJoin(i){const list=items,prev=list[Math.max(0,i-1)];selected=i;render();loadAt(list,Math.max(0,i-1),true,changed()?'YOUR CUT':'ORIGINAL',Math.max(prev.in,prev.out-1.5));}
function choose(id,restoreDraft=true){stop();p=example(id)||D.examples[0];items=canonical();history=[];selected=0;revealed=false;blind=Math.random()<.5;if(restoreDraft){try{let saved=JSON.parse(localStorage.getItem('cineosis.operative.'+p.id));if(saved){validate(saved,D);items=saved.items;}}catch{say('Saved draft could not be read; the original is loaded.')}}$('#readingTitle').textContent=names[p.type];$('#exampleTitle').textContent=p.title;$('#claim').textContent=p.claim;$('#scope').textContent=p.source==='duck'?'INSTRUCTIONAL EXTENSION':'FICTION · EDITORIAL READING';document.querySelectorAll('[data-example]').forEach(b=>b.classList.toggle('selected',b.dataset.example===id));render();loadAt(items,0,false,changed()?'YOUR CUT':'ORIGINAL');historyURL();say(`${D.sources[p.source].title} · ${time(p.start)}–${time(p.end)} · ${changed()?'saved cut restored':'annotated original loaded'}`)}
function historyURL(){const u=new URL(location.href);u.searchParams.set('example',p.id);window.history.replaceState(null,'',u)}
function evidence(joinIndex){let x=items[selected],ex=example(x.example),source=D.sources[ex.source],relation=joinIndex?joins(items)[joinIndex-1]:null;$('#detailsBody').innerHTML=`<p class="source">${esc(source.title)} (${source.year}) · ${time(p.start)}–${time(p.end)}</p><h2>${esc(names[p.type])}</h2><p>${esc(p.claim)}</p><h3>Rival reading</h3><p>${esc(p.rival)}</p><h3>Scope</h3><p>${esc(p.limit)}</p><h3>${relation?'Selected join':'Selected block'}</h3><p>${relation?esc(relation.left.label+' → '+relation.right.label):esc(x.label+' · '+x.unit+' · '+sign(x.sign).symbol+': '+x.signEvidence)}</p><p class="source">${esc(p.reader)} · ${esc(p.readingStatus)}</p><p>${esc(p.inspection)}</p><p>${esc(source.sound)}</p><p><a target="_blank" rel="noopener" href="${esc(source.url)}">Complete source edition ↗</a>${source.archive?` · <a target="_blank" rel="noopener" href="${esc(source.archive)}">Moving Image Archive title ↗</a>`:''}</p><p class="small">Times refer to the specified Internet Archive file. Editions are not automatically aligned. Sound in a recut moves with each block.</p>`;$('#details').showModal()}
function showSign(id){paletteSign=id;let s=sign(id),matches=[];for(const ex of D.examples)for(const b of ex.blocks)if(b.sign===id)matches.push({ex,b});$('#signMatches').innerHTML=`<p><b>${esc(s.symbol)} · ${esc(s.name)}</b> ${esc(s.question)}</p><p>${esc(s.difference)}</p>`+(matches.length?matches.map(m=>`<button data-match="${m.ex.id}:${m.b.id}">${esc(m.b.label)} ↗</button>`).join(''):'<p>No inspected realization in this six-passage set. No shot is assigned merely to fill this sign.</p>');}
function exportCut(){const doc={format:'cineosis-operative/1',base:p.id,items,sourceReading:p,events:edl(items,D),made:new Date().toISOString(),note:'Edited order is not automatically assigned the original syntagm.'};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}));a.download=`syntagm-${p.id}-cut.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);say('Exported the cut, source times, signs and baseline evidence.')}
async function init(){D=await(await fetch('syntagm/operative/examples.json')).json();$('#specimens').innerHTML=D.examples.map(ex=>`<button class="specimen" data-example="${ex.id}"><img src="${ex.poster}" alt="${esc(ex.title)}"><b>${esc(names[ex.type].replace(' syntagma',''))}</b><span>${esc(ex.title)}</span></button>`).join('');$('#signs').innerHTML=D.signs.map(s=>`<button data-sign="${s.n}" class="${D.examples.some(e=>e.blocks.some(b=>b.sign===s.n))?'used':''}" style="grid-column:${s.col+1};grid-row:${s.row+1}" title="${esc(s.name)}">${esc(s.symbol)}</button>`).join('');choose(params.get('example')||'telephone');stageTo('find');tick();}
for(const b of document.querySelectorAll('[data-stage]'))b.onclick=()=>stageTo(b.dataset.stage);
$('#specimens').onclick=e=>{const b=e.target.closest('[data-example]');if(b)choose(b.dataset.example)};
$('#nodes').onclick=e=>{let n=e.target.closest('[data-node]'),j=e.target.closest('[data-join]');if(n){const i=+n.dataset.node,list=copy(displayList);selected=Math.max(0,items.findIndex(x=>x.uid===list[i].uid));render();loadAt(list,i,true,activeMode)}else if(j){const i=+j.dataset.join,list=copy(displayList);loadAt(list,i-1,true,activeMode,Math.max(list[i-1].in,list[i-1].out-1.5))}};
$('#nodes').onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.join){e.preventDefault();playJoin(+e.target.dataset.join)}};
function togglePlay(){if(wanted&&!v.paused){stop();return;}if(!sequence.length||v.currentTime>=sequence.at(-1).out-.05&&index===sequence.length-1)playItems(items,changed()?'YOUR CUT':'ORIGINAL');else loadAt(sequence,index,true,activeMode,Math.min(sequence[index].out-.05,Math.max(sequence[index].in,v.currentTime)))}
$('#play').onclick=togglePlay;$('#bigPlay').onclick=togglePlay;
$('#mute').onclick=()=>{v.muted=!v.muted;$('#mute').textContent=v.muted?'Sound off':'Sound on'};
$('#scrub').oninput=()=>{let t=+$('#scrub').value,i=0;while(i<sequence.length-1&&t>=sequence[i].out-sequence[i].in){t-=sequence[i].out-sequence[i].in;i++}loadAt(sequence,i,wanted,activeMode,Math.min(sequence[i].out-.03,sequence[i].in+t))};
$('#restore').onclick=()=>{commit(canonical(),'Original order and durations restored.');selected=0;render();loadAt(items,0,false,'ORIGINAL')};
for(const b of document.querySelectorAll('[data-op]'))b.onclick=()=>commit(transform(items,b.dataset.op,++seed),`${b.textContent}: the source intervals have been rearranged.`);
$('#left').onclick=()=>{if(selected<1)return;const a=copy(items);[a[selected-1],a[selected]]=[a[selected],a[selected-1]];selected--;commit(a,'Moved one block earlier.')};
$('#right').onclick=()=>{if(selected>=items.length-1)return;const a=copy(items);[a[selected+1],a[selected]]=[a[selected],a[selected+1]];selected++;commit(a,'Moved one block later.')};
$('#remove').onclick=()=>{if(items.length>1)commit(items.filter((x,i)=>i!==selected),'Removed the selected block.')};
$('#duplicate').onclick=()=>{if(items.length>=64)return;const a=copy(items),x=copy(a[selected]);x.uid=x.id+'-'+crypto.randomUUID().slice(0,8);a.splice(selected+1,0,x);commit(a,'Repeated the selected interval.')};
$('#length').oninput=()=>{$('#lengthValue').textContent=(+$('#length').value).toFixed(1)+'s'};
$('#length').onchange=()=>{let a=copy(items);a[selected].out=a[selected].in+Number($('#length').value);commit(a,'Changed the selected duration.')};
$('#undo').onclick=()=>{if(!history.length)return;stop();items=history.pop();selected=Math.min(selected,items.length-1);render();persist();loadAt(items,selected,false,changed()?'YOUR CUT':'ORIGINAL');say('Previous cut restored.')};
$('#playOriginal').onclick=()=>playItems(canonical(),'ORIGINAL');$('#playVariant').onclick=()=>playItems(items,'YOUR CUT');
$('#suggested').onclick=()=>commit(transform(canonical(),p.operation),'Test variant built from the original.');
$('#compareA').onclick=()=>{playItems(blind?items:canonical(),revealed?`A · ${blind?'YOUR CUT':'ORIGINAL'}`:'A');say('Playing A. Compare the actual action, not just the switch count.')};
$('#compareB').onclick=()=>playItems(blind?canonical():items,revealed?`B · ${blind?'ORIGINAL':'YOUR CUT'}`:'B');
$('#reveal').onclick=()=>{revealed=!revealed;renderTest()};$('#differences').onclick=e=>{const b=e.target.closest('[data-diff]');if(b)playJoin(+b.dataset.diff)};
$('#why').onclick=()=>evidence();$('#more').onclick=()=>$('#menu').showModal();for(const b of document.querySelectorAll('.close'))b.onclick=()=>b.closest('dialog').close();
$('#toggleTable').onclick=()=>{let show=$('#palette').hidden;$('#palette').hidden=!show;$('#specimens').hidden=show;$('#toggleTable').textContent=show?'Passage examples':'45-sign palette';if(show)showSign(paletteSign||items[selected].sign)};
$('#signs').onclick=e=>{const b=e.target.closest('[data-sign]');if(b)showSign(b.dataset.sign)};
$('#signMatches').onclick=e=>{const b=e.target.closest('[data-match]');if(!b)return;const [ex,id]=b.dataset.match.split(':');const match=example(ex).blocks.find(b=>b.id===id);$('#detailsBody').innerHTML=`<h2>${esc(sign(match.sign).name)}</h2><p>${esc(match.signEvidence)}</p><p>${esc(D.sources[example(ex).source].title)} · ${time(match.start)}–${time(match.end)}</p><div class="actions"><button id="auditionMatch">Play in original</button><button id="substituteMatch">Substitute selected block</button></div>`;$('#details').showModal();$('#auditionMatch').onclick=()=>{choose(ex,false);selected=items.findIndex(x=>x.id===id);render();loadAt(items,selected,true,'ORIGINAL');$('#details').close()};$('#substituteMatch').onclick=()=>{let x=makeItems(example(ex)).find(x=>x.id===id);x.uid=x.id+'-'+crypto.randomUUID().slice(0,8);let a=copy(items);a[selected]=x;commit(a,'Substituted a real source interval. Original syntagm no longer transfers.');$('#details').close();stageTo('bond')};};
$('#exportCut').onclick=exportCut;$('#exportMenu').onclick=exportCut;$('#importCut').onclick=$('#importMenu').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{try{let doc=JSON.parse(await e.target.files[0].text());validate(doc,D);choose(doc.base,false);commit(doc.items,'Imported the cut and its source intervals.');$('#menu').close();stageTo('cut')}catch(err){say('Import rejected: '+err.message)}finally{e.target.value=''}};
$('#retry').onclick=()=>{v.removeAttribute('src');loadAt(sequence.length?sequence:items,index,false,activeMode)};
v.addEventListener('ended',()=>{if(wanted&&index<sequence.length-1)loadAt(sequence,index+1,true,activeMode);else{wanted=false;$('#play').textContent='↺ Replay';$('#bigPlay').hidden=false}});
let touch;$('#workspace').addEventListener('touchstart',e=>{if(e.target.closest('button,input,a'))return;touch=[e.touches[0].clientX,e.touches[0].clientY]},{passive:true});$('#workspace').addEventListener('touchend',e=>{if(!touch)return;let dx=e.changedTouches[0].clientX-touch[0],dy=e.changedTouches[0].clientY-touch[1];touch=null;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.5){const i=stages.indexOf(stage);stageTo(stages[Math.max(0,Math.min(3,i+(dx<0?1:-1)))])}},{passive:true});
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.target.closest('input,button,textarea,dialog')){e.preventDefault();togglePlay()}});
init().catch(e=>say('Could not load the annotated examples: '+e.message));
