export const copy=x=>JSON.parse(JSON.stringify(x));
export function duration(items){return items.reduce((n,x)=>n+x.out-x.in,0)}
export function switches(items){return items.slice(1).reduce((n,x,i)=>n+(x.strand!==items[i].strand),0)}
export function joins(items){return items.slice(1).map((x,i)=>({left:items[i],right:x,key:`${items[i].uid}>${x.uid}`}))}
export function transform(items,op,seed=17){let a=copy(items);if(op==='reverse')return a.reverse();if(op==='group')return a.sort((x,y)=>x.strand.localeCompare(y.strand));if(op==='halve')return a.map(x=>({...x,out:x.in+(x.out-x.in)/2}));if(op==='shuffle'){let r=seed>>>0;for(let i=a.length-1;i>0;i--){r=(Math.imul(r,1664525)+1013904223)>>>0;let j=r%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a}return a}
export function shuffledStats(items,n=499){let values=Array.from({length:n},(_,i)=>switches(transform(items,'shuffle',i+1)));return {observed:switches(items),mean:values.reduce((a,b)=>a+b,0)/n,min:Math.min(...values),max:Math.max(...values),values};}
export function makeItems(p){return p.blocks.map(x=>({...x,uid:x.id,example:p.id,in:x.start-p.start,out:x.end-p.start}))}
export function edl(items,data){let t=0;return items.map((x,i)=>{let p=data.examples.find(p=>p.id===x.example),s=data.sources[p.source],dur=x.out-x.in;const e={n:i+1,record:[t,t+dur],media:p.media,mediaRange:[x.in,x.out],source:s.download,sourceRange:[p.start+x.in,p.start+x.out],strand:x.strand,sign:x.sign,signEvidence:x.signEvidence,block:x.id};t+=dur;return e})}
export function validate(doc,data){if(doc?.format!=='cineosis-operative/1'||!Array.isArray(doc.items)||doc.items.length<1||doc.items.length>64)throw Error('Expected an operative cut with 1–64 blocks.');let ids=new Set;for(const x of doc.items){let p=data.examples.find(p=>p.id===x.example),b=p?.blocks.find(b=>b.id===x.id);if(!b||!Number.isFinite(x.in)||!Number.isFinite(x.out)||x.in<b.start-p.start-.01||x.out>b.end-p.start+.01||x.out-x.in<.1||typeof x.uid!=='string'||ids.has(x.uid)||!data.signs.some(s=>s.n===x.sign)||x.strand!==b.strand)throw Error('Invalid block, source range, sign or strand.');ids.add(x.uid);}if(!data.examples.some(x=>x.id===doc.base))throw Error('Unknown baseline.');return true}
