import {MODES,phrases,compose,measures} from './model.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const status=s=>$('status').textContent=s,base=new URL('../',import.meta.url),media=s=>new URL(s,base).href;
let cases,shots,cache,selected,plan,original,flat,pools,texts,goalPool,variant=0,locks={},current=0,playing=false,token=0,hold=0,last=0,searchPool=[],timed=null,audioURL=null,trial='study',corrections=0,recognition,busy=false;
const film=$('film'),voice=$('voice');
const fmt=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
function tab(id){document.querySelectorAll('.pane').forEach(x=>x.hidden=x.id!==id);document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-selected',String(x.dataset.tab===id)));}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
$('mode').innerHTML=Object.entries(MODES).map(([k,v])=>`<option value="${k}">${v[0]} · ${v[1]}</option>`).join('');
for(const [button,dialog,open] of [['shelfOpen','shelf',true],['shelfClose','shelf',false],['aboutOpen','about',true],['aboutClose','about',false]])$(button).onclick=()=>open?$(dialog).showModal():$(dialog).close();
function showShelf(){const q=$('filter').value.toLowerCase();$('shelfList').innerHTML=cases.filter(c=>(c.title+' '+c.author+' '+c.theme).toLowerCase().includes(q)).map(c=>`<article class="testCard"><span class="badge">${esc(c.theme)}</span><h3>${esc(c.title)}</h3><small>${esc(c.author)}</small><p>${esc(c.goal)}</p><p>${esc(c.question)}</p><button data-load="${c.id}">${c.text?'Use text':'Try study brief'}</button><a href="${esc(c.source)}" target="_blank" rel="noopener">${c.source.includes('google.com')?'Find text':'Source'}</a><p>${esc(c.textStatus)}</p></article>`).join('');$('shelfList').querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>loadCase(cases.find(c=>c.id===b.dataset.load)));}
$('filter').oninput=showShelf;
function loadCase(c){stop();judgement='unreviewed';$('review').value='';selected=c;locks={};corrections=0;variant=0;timed=null;trial=c.text?'text':'study';$('inputTitle').textContent=c.title;$('textStatus').textContent=c.textStatus;$('text').value=c.text||c.brief;$('goal').value=c.goal;$('mode').value=c.mode;$('testTitle').textContent=c.title;$('question').textContent=c.question;$('shelf').close();tab('compose');status('Ready · '+(c.text?'source text':'original study brief')+' · Compose film');}
let encoder,requestId=0;const waiting=new Map();
function browserRetrieve(texts){
 if(!encoder){encoder=new Worker(new URL('./encoder-worker.mjs',import.meta.url),{type:'module'});encoder.onmessage=e=>{if(e.data.progress)return status(e.data.progress);const p=waiting.get(e.data.id);if(!p)return;waiting.delete(e.data.id);e.data.error?p.reject(Error(e.data.error)):p.resolve(e.data.rows);};encoder.onerror=()=>{waiting.forEach(p=>p.reject(Error('Browser encoder unavailable. Cached studies remain ready.')));waiting.clear();encoder.terminate();encoder=null;};}
 return new Promise((resolve,reject)=>{const id=++requestId;waiting.set(id,{resolve,reject});encoder.postMessage({id,texts});});
}
async function retrieve(qs){
 const missing=[...new Set(qs.filter(q=>!cache[q]))];if(missing.length){
  let rows;
  if(['127.0.0.1','localhost'].includes(location.hostname)){
   try{const r=await fetch(new URL('../api/shannon/retrieve',base),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({texts:missing}),signal:AbortSignal.timeout(120000)});if(r.ok)rows=(await r.json()).rows;}catch{}
  }
  if(!rows)rows=await browserRetrieve(missing);
  if(rows.length!==missing.length)throw Error('Retrieval response is incomplete.');missing.forEach((q,i)=>cache[q]=rows[i]);
 }
 return qs.map(q=>cache[q]);
}
function busySet(on){busy=on;for(const id of ['build','another','searchButton','searchFilm','allTests'])$(id).disabled=on;}
function align(p){if(!timed||timed.length!==p.scenes.length)return p;let items=[];p.scenes.forEach((s,i)=>{const t=timed[i],duration=(timed[i+1]?.start??t.end)-t.start,old=s.items.reduce((a,x)=>a+x.duration,0);let at=t.start;s.items.forEach(x=>{const proposed=x.duration/old*duration,available=x.out-x.in;x.duration=proposed;x.out=x.in+Math.min(available,proposed);x.hold=Math.max(0,proposed-available);x.recordIn=at;at+=proposed;});items.push(...s.items);});p.items=items;p.duration=items.at(-1).recordIn+items.at(-1).duration;return p;}
async function build(){if(busy)return;busySet(true);stop();judgement='unreviewed';try{const raw=$('text').value.trim();texts=timed?timed.map(t=>t.text):phrases(raw);if(!texts.length)throw Error('Add some words first.');if(texts.length>120)throw Error('Use up to 120 scenes per cut. Group lines with blank lines for longer works.');
 const qs=[...texts,...($('goal').value.trim()?[$('goal').value.trim()]:[])],r=await retrieve(qs);pools=r.slice(0,texts.length);goalPool=r[texts.length]||[];
 const opts={texts,pools,goalPool,shots,mode:$('mode').value,seconds:+$('length').value,variant,locks};original=align(compose(opts));flat=align(compose({...opts,locks:{},baseline:true}));plan=original;render();load(0);tab('cut');status(`${plan.scenes.length} scenes · ${plan.items.length} shots · ${fmt(plan.duration)} · ready to watch`);
 }catch(e){status(e.message);}finally{busySet(false);}}
$('build').onclick=build;$('another').onclick=()=>{variant++;build();};
function render(){
 $('play').disabled=false;$('scrub').max=plan.duration;$('cutTitle').textContent=`${plan.scenes.length} scenes · ${plan.items.length} shots`;
 $('scenes').innerHTML=plan.scenes.map((s,i)=>{const a=shots[s.anchor];return `<article class="scene" data-scene="${i}"><div class="sceneHead"><img loading="lazy" src="${esc(media(a.poster))}" alt=""><div><p>${i+1}. ${esc(s.text)}</p><small>${esc(a.title)} · ${s.items.length} shot${s.items.length===1?'':'s'}</small></div></div><small>${esc(s.reason)}</small><div class="sceneTools"><button data-watch="${i}">Watch scene</button><button data-lock="${i}">${locks[i]?'Unlock':'Lock'}</button><button data-options="${i}">Replace</button></div><div id="alts-${i}" class="alternatives" hidden>${s.alternatives.map(([id,v])=>`<button data-replace="${i}" data-id="${id}" title="${esc(shots[id].title)}"><img loading="lazy" alt="" src="${esc(media(shots[id].poster))}"><span>${esc(shots[id].title.slice(0,40))}</span></button>`).join('')}</div><details><summary>Selection evidence</summary><small>Similarity ${s.coverage.toFixed(3)} · candidate entropy ${s.H.toFixed(2)} bits · surprisal ${s.surprisal===null?'outside candidate set':s.surprisal.toFixed(2)+' bits'}. These describe retrieval, not whether this scene works.</small></details></article>`;}).join('');
 $('scenes').querySelectorAll('[data-watch]').forEach(b=>b.onclick=()=>{load(plan.items.findIndex(x=>x.scene===+b.dataset.watch));play();});
 $('scenes').querySelectorAll('[data-options]').forEach(b=>b.onclick=()=>{const e=$('alts-'+b.dataset.options);e.hidden=!e.hidden;});
 $('scenes').querySelectorAll('[data-lock]').forEach(b=>b.onclick=()=>{let i=+b.dataset.lock;if(locks[i])delete locks[i];else locks[i]=plan.scenes[i].anchor;render();status('Lock updated. Compose again to plan around it.');});
 $('scenes').querySelectorAll('[data-replace]').forEach(b=>b.onclick=()=>{locks[+b.dataset.replace]=b.dataset.id;corrections++;build();});
 if(original&&flat){const a=measures(original,shots),b=measures(flat,shots);$('metrics').innerHTML='<table><tr><th>Observed edit</th><th>Composed</th><th>Retrieval only</th></tr>'+['scenes','shots','sources','returns','heldSeconds'].map(k=>`<tr><td>${esc(k.replace('heldSeconds','Held seconds'))}</td><td>${Number(a[k]).toFixed(k==='heldSeconds'?1:0)}</td><td>${Number(b[k]).toFixed(k==='heldSeconds'?1:0)}</td></tr>`).join('')+'</table><p>No automatic semantic verdict.</p>';}
}
function stop(){playing=false;film.pause();voice.pause();$('play').textContent='Play cut';}
async function play(){if(!plan)return;playing=true;$('play').textContent='Pause';try{if(!hold)await film.play();if(audioURL){voice.currentTime=plan.items[current].recordIn+Math.max(0,film.currentTime-plan.items[current].in)+hold;await voice.play();}}catch(e){stop();status('Tap Play to allow playback, or inspect the unavailable source.');}}
function load(i,offset=0){if(!plan?.items[i])return;const keep=playing;film.pause();const x=plan.items[i],s=shots[x.id],key=++token;current=i;hold=0;$('empty').hidden=true;$('mediaRetry').hidden=true;$('screenLabel').textContent=`${x.scene+1} / ${plan.scenes.length} · ${plan.scenes[x.scene].text}`;film.poster=media(s.poster);film.src=media(s.url);$('scrub').value=x.recordIn+offset;$('clock').textContent=fmt(x.recordIn+offset);document.querySelectorAll('.scene').forEach(el=>el.classList.toggle('active',+el.dataset.scene===x.scene));film.onloadedmetadata=()=>{if(key!==token)return;if(film.duration+0.1<x.out){stop();status('Source shorter than catalogued interval. Replace this scene.');return;}film.currentTime=x.in+Math.min(offset,x.out-x.in-.01);if(offset>x.out-x.in)hold=offset-(x.out-x.in);if(keep)play();};film.onerror=()=>{if(key!==token)return;stop();$('mediaRetry').hidden=false;status('Source could not load. Retry or replace this scene; the edit is preserved.');};}
$('play').onclick=()=>playing?stop():play();$('mediaRetry').onclick=()=>load(current);$('previous').onclick=()=>load(Math.max(0,plan.items.findIndex(x=>x.scene===Math.max(0,plan.items[current].scene-1))));$('sound').onclick=()=>{film.muted=!film.muted;$('sound').textContent=film.muted?'Sound off':'Sound on';};
function next(){if(current+1<plan.items.length)load(current+1);else{stop();status('End of cut · record your reading in Test');}}
function tick(now){const dt=Math.min(.1,(now-last)/1000||0);last=now;if(playing&&plan&&film.readyState>=2){const x=plan.items[current];let elapsed=Math.max(0,film.currentTime-x.in);if(film.currentTime>=x.out-.04||film.ended||hold){film.pause();if(x.hold){hold+=dt;elapsed=x.out-x.in+hold;if(hold>=x.hold)next();}else next();}const t=x.recordIn+Math.min(elapsed,x.duration);$('scrub').value=t;$('clock').textContent=fmt(t);}requestAnimationFrame(tick);}requestAnimationFrame(tick);
$('scrub').oninput=()=>{if(!plan)return;const t=+$('scrub').value,i=plan.items.findIndex(x=>x.recordIn+x.duration>t);load(i<0?plan.items.length-1:i,t-plan.items[i<0?plan.items.length-1:i].recordIn);if(audioURL)voice.currentTime=t;};
$('baseline').onclick=()=>{if(!flat)return status('Compose a cut first.');stop();plan=flat;render();load(0);play();status('Playing independent phrase retrieval');};$('composed').onclick=()=>{if(!original)return status('Compose a cut first.');stop();plan=original;render();load(0);play();status('Playing the composed path');};
async function search(){if(busy)return;const q=$('query').value.trim();if(!q)return;busySet(true);try{[searchPool]=await retrieve([q]);$('results').innerHTML=searchPool.slice(0,20).map(([id,v])=>{const s=shots[id];return `<article class="result"><img loading="lazy" alt="" src="${esc(media(s.poster))}"><div><p>${esc(s.title)} · ${fmt(s.start)}<br><small>Similarity ${v.toFixed(3)}</small></p><button data-preview="${id}">Watch passage</button><button data-use="${id}">Use in scene</button></div></article>`;}).join('');$('results').querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>{stop();plan=compose({texts:[q],pools:[searchPool],shots,locks:{0:b.dataset.preview},seconds:15});render();load(0);play();});$('results').querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{if(!original){$('text').value=q;locks={0:b.dataset.use};}else{locks[original.items[Math.min(current,original.items.length-1)].scene]=b.dataset.use;}corrections++;build();});status('Archive results · open a passage or compose a sequence');}catch(e){status(e.message);}finally{busySet(false);}}
$('searchButton').onclick=search;$('query').onkeydown=e=>{if(e.key==='Enter')search();};$('searchFilm').onclick=()=>{const q=$('query').value.trim();if(!q)return;$('text').value=q;timed=null;locks={};$('inputTitle').textContent='Search into sequence';trial='custom';build();};
function download(name,data){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('export').onclick=()=>{if(!plan)return status('Compose a cut first.');download('cineosis-shannon-edit.json',{...plan,timedTranscript:timed,work:selected?.title,trial,goal:$('goal').value,corrections,sources:Object.fromEntries([...new Set(plan.items.map(x=>x.id))].map(id=>[id,shots[id]])),audio:audioURL?{filename:$('audioNote').dataset.filename||'attached recording',embedded:false}:null});};
let judgement='unreviewed';$('pass').onclick=()=>{judgement='works';status('Marked works · Save review to keep it');};$('fail').onclick=()=>{judgement='needs revision';status('Marked needs revision · Save review to keep it');};
function review(){return {date:new Date().toISOString(),work:selected?.id||'custom',trial,text:$('text').value,goal:$('goal').value,question:$('question').textContent,judgement,note:$('review').value,corrections,metrics:original?measures(original,shots):null,edit:original};}
$('saveReview').onclick=()=>{if(!original)return status('Compose a cut before reviewing.');const r=review();try{const all=JSON.parse(localStorage.getItem('shannon-reviews')||'[]');all.push(r);localStorage.setItem('shannon-reviews',JSON.stringify(all));}catch{}download('shannon-review.json',r);status('Review saved and downloaded');};
$('text').oninput=()=>{trial='user text';timed=null;locks={};$('textStatus').textContent='Your text · scene timing estimated from word counts';};
function subtitles(t){const time=s=>s.split(':').reduce((a,v)=>a*60+Number(v.replace(',','.')),0);return t.replace(/\r/g,'').split(/\n\s*\n/).map(b=>{const lines=b.split('\n'),ix=lines.findIndex(l=>l.includes('-->'));if(ix<0)return null;const [a,z]=lines[ix].split('-->').map(x=>x.trim().split(/\s+/)[0]);return {start:time(a),end:time(z),text:lines.slice(ix+1).join(' ').replace(/<[^>]*>/g,'')};}).filter(x=>x&&x.text&&Number.isFinite(x.start)&&x.end>x.start);}
$('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.type.startsWith('audio/')||/\.(mp3|wav|m4a|ogg)$/i.test(f.name)){if(audioURL)URL.revokeObjectURL(audioURL);audioURL=URL.createObjectURL(f);voice.src=audioURL;$('audioPanel').hidden=false;$('audioNote').dataset.filename=f.name;status('Recording attached. Add its transcript or timed subtitles to compose.');return;}const t=await f.text();try{if(/\.(srt|vtt)$/i.test(f.name)){timed=subtitles(t);if(!timed.length)throw Error('No valid subtitle cues.');if(timed.some((x,i)=>i&&x.start<timed[i-1].end))throw Error('Overlapping cues: merge speaker overlaps before composing.');$('text').value=timed.map(x=>x.text).join('\n\n');$('textStatus').textContent=`${timed.length} timed cues · original recording clock`;}else{$('text').value=t;timed=null;$('textStatus').textContent='Imported transcript · estimated timing';}trial='imported text';locks={};status('Imported '+f.name);}catch(e){timed=null;status(e.message);}};
const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){$('speak').disabled=true;$('speak').title='Speech recognition unavailable in this browser';}else{$('speak').onclick=()=>{if(recognition){recognition.stop();return;}recognition=new Speech();recognition.continuous=true;recognition.interimResults=false;recognition.lang=document.documentElement.lang||'en-US';recognition.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)$('text').value+=($('text').value?'\n':'')+e.results[i][0].transcript;trial='speech transcript';timed=null;};recognition.onend=()=>{recognition=null;$('speak').textContent='Speak';};recognition.onerror=e=>status('Speech input: '+e.error);recognition.start();$('speak').textContent='Stop mic';status('Listening. Compose after the passage is complete.');};}
$('allTests').onclick=async()=>{if(busy)return;busySet(true);const rows=[];try{for(const c of cases){const ts=phrases(c.text||c.brief),pp=await retrieve([...ts,c.goal]),p=compose({texts:ts,pools:pp.slice(0,ts.length),goalPool:pp.at(-1),shots,mode:c.mode,seconds:60});rows.push({work:c.id,input:c.text?'text':'study brief',...measures(p,shots),bounds:p.items.every(x=>x.in>=0&&x.out<=shots[x.id].duration+.01),semanticVerdict:'unreviewed'});$('testLog').textContent=`Checked ${rows.length}/${cases.length} · ${c.title}`;await new Promise(r=>setTimeout(r,0));}download('shannon-shelf-checks.json',rows);$('testLog').textContent=rows.map(r=>`${r.bounds?'Bounds valid':'Bounds failed'} · ${r.work} · ${r.input} · ${r.shots} shots · meaning unreviewed`).join('\n');status('Shelf checks complete · screening judgements remain open');}catch(e){status(e.message);}finally{busySet(false);}};
try{[cases,shots,cache]=await Promise.all(['tests.json','shots.json','retrieval.json'].map(async p=>{const r=await fetch(new URL(p,import.meta.url));if(!r.ok)throw Error('Archive data unavailable');return r.json();}));$('testCount').textContent=cases.length;$('archiveInfo').textContent=`This build indexes ${Object.keys(shots).length.toLocaleString()} archive shots and caches ${Object.keys(cache).length} exact phrase queries. Additional footage is not claimed unless it appears in this index.`;showShelf();loadCase(cases.find(c=>c.id==='basho'));if(new URLSearchParams(location.search).has('tests'))$('shelf').showModal();}catch(e){status(e.message+' · reload to retry');}
