"""Editorial study briefs are original descriptions, never substitutes for source poems."""
import json
from pathlib import Path
P=Path(__file__).parent
rows=[
('keats','Ode on a Grecian Urn','John Keats','Frozen action','A carved figure is about to move. A lover approaches but never reaches the beloved. A procession leaves a town empty. The object remains while its viewers pass.','Hold an unfinished action through changing contexts.','Do lovers remain suspended, rather than simply cutting to a vase?','return'),
('berry','The Peace of Wild Things','Wendell Berry','Anxiety to rest','A person wakes in a dark room. Water birds rest beside still water. The person attends to the quiet surface. The final scene settles without resolving the world outside.','Move from vigilance to a sustained refuge.','Does the pacing change, and does the refuge have time to register?','arrive'),
('cavafy','Ithaka','C. P. Cavafy','Journey and arrival','A traveller leaves a harbour. Markets and unfamiliar streets interrupt the route. The journey accumulates encounters. A quiet shore becomes an arrival altered by the journey.','Let encounters outweigh the destination.','Is the arrival changed by what precedes it?','journey'),
('coleridge','Kubla Khan','Samuel Taylor Coleridge','World and rupture','A palace stands beside a river. Gardens open into wild ground. Water descends into a dark chasm. A performer recalls a world that cannot be fully recovered.','Build a place, rupture it, then attempt a return.','Does the rupture alter the organisation rather than merely change scenery?','contrast'),
('schleicher','The Sheep and the Horses','August Schleicher','Unequal labour','A sheep watches horses carry heavy loads. A human directs their labour. The animals confront the unequal arrangement. The sheep departs.','Develop a fable across distinct agents.','Can the observer, workers and owner be distinguished?','journey'),
('basho','Old Pond','Matsuo Bashō','Event and aftermath','An old pond lies still. A frog enters the water. Ripples expand and subside.','Give one event a before and an after.','Is the disturbance legible without a cut for each noun?','arrive'),
('zhuangzi','Cook Ding','Zhuangzi','Skill in motion','A cook prepares to cut an ox. Hands move through the joints with little resistance. A difficult point interrupts the rhythm. Work resumes and the blade is put away.','Make skilled action, hesitation and release perceptible.','Does the difficult moment change duration before the release?','journey'),
('williams','The Red Wheelbarrow','William Carlos Williams','Attention to relations','A red wheelbarrow holds rain. White chickens move beside it. The wet surface catches the light. The arrangement remains.','Sustain one spatial arrangement.','Does the cut preserve adjacency rather than scatter isolated objects?','hold'),
('wilbur','Mind','Richard Wilbur','Thought and obstacle','A bat moves inside a dark room. Its path bends around walls. A gap opens and the movement changes.','Test an analogy through constrained movement.','Does the pattern of movement do more than illustrate a bat?','journey'),
('auden','The Shield of Achilles','W. H. Auden','Expectation and refusal','A viewer anticipates a flourishing city. An empty plain replaces it. Ordered crowds stand before impersonal violence. The crafted surface offers no consoling return.','Make the image refuse an established expectation.','Does the second world contradict the first without collapsing into random contrast?','contrast'),
('homer','Iliad 18: Shield of Achilles','Homer','World within an object','A smith works metal. A city celebrates while another prepares for war. Fields are ploughed and harvested. Dancers gather. The enclosing surface returns.','Construct several worlds inside a shared frame.','Can civic, martial and agricultural scenes remain distinct within the whole?','return'),
('lem','Love and Tensor Algebra / Trurl’s Electronic Bard','Stanisław Lem','Abstract desire','A machine addresses another machine. Repeated geometrical forms approach one another. A mechanical barrier interrupts their convergence. The pattern returns with a changed interval.','Make a formal pattern carry an address.','Does repetition develop an expressive relation rather than decorate the words?','return'),
('mon','non/tot III','Franz Mon','Spatial language','A mark appears on a blank field. Similar marks accumulate with uneven gaps. A gap displaces the centre of attention. The arrangement breaks apart.','Compose intervals and placement as events.','Does the cut respond to spacing rather than invent a narrative?','contrast'),
('angelou','Still I Rise','Maya Angelou','Refrain and agency','A figure confronts a hostile crowd. The figure stands and advances. Pressure returns. The figure occupies more of the frame and continues.','Let recurrence accumulate agency.','Does each return change the force of the refrain?','return'),
('thomas','Do Not Go Gentle into That Good Night','Dylan Thomas','Refrain and urgency','An aging face watches fading light. Several lives appear in succession. The same gesture returns with increasing urgency. An intimate address ends the passage.','Escalate a refrain without losing its identity.','Does recurrence intensify rather than merely repeat footage?','return'),
('frost','The Road Not Taken','Robert Frost','Choice and retelling','Two woodland paths appear equally worn. A traveller chooses one. The unused path disappears from view. The traveller later recounts the choice as a difference.','Preserve the tension between choice and its retelling.','Does the opening keep the alternatives comparable?','contrast'),
('holderlin','In Lovely Blueness','Friedrich Hölderlin','Dwelling and measure','A church tower rises into blue sky. A person inhabits a modest room. The view expands from dwelling to sky. The human figure remains small within the scale.','Move between dwelling and an ungraspable measure.','Does the change of scale develop a relation rather than become a landscape reel?','arrive'),
('george','The Word / Das Wort','Stefan George','Naming and loss','A traveller brings an object home. An inscription is sought for it. No inscription arrives. The object disappears from the arrangement.','Make absence follow a failed act of naming.','Is the missing object established before its absence matters?','return'),
('stevens','Thirteen Ways of Looking at a Blackbird','Wallace Stevens','One motif, many relations','A dark bird crosses a snowy field. A bird becomes a silhouette in a window. Human activity changes the surrounding scale. The dark shape returns in a different landscape.','Change the relation while retaining the motif.','Can a repeated figure remain recognisable across distinct scenes?','return'),
('macleish','Ars Poetica','Archibald MacLeish','Presence and duration','A worn object rests in a hand. A window opens onto evening. Traces of an absent person remain in a room. The final image is allowed to persist.','Let material presence support an indirect reading.','Does the closing image have duration beyond illustration?','hold'),
('hopkins','Felix Randal','Gerard Manley Hopkins','Labour and care','A smith works at a forge. Illness interrupts the work. Another person tends the sick worker. The empty forge recalls the earlier strength.','Relate former labour to present care.','Does the final return transform the opening workplace?','return'),
('knowles','The House of Dust','Alison Knowles and James Tenney','Combinatorial dwelling','A house is made of earth. Another dwelling stands near water. A shelter is lit at night. Different inhabitants enter each construction.','Vary material, place, light and inhabitants independently.','Can one factor change while the others remain held?','contrast'),
('brautigan','All Watched Over by Machines of Loving Grace','Richard Brautigan','Ecology and machine','Animals move through a meadow. Machines operate nearby. Human work and animal rest alternate. A wide scene leaves their relationship unresolved.','Keep harmony and control available as rival readings.','Does the sequence leave a meaningful ambiguity rather than certify a utopia?','alternate'),
('nursery','Hey Diddle Diddle','Traditional','Impossible event','Hey diddle diddle,\nThe cat and the fiddle,\nThe cow jumped over the moon;\nThe little dog laughed\nTo see such sport,\nAnd the dish ran away with the spoon.','Build a playful sequence of impossible actions.','Are unlikely events composed into a progression?','journey'),
('meeting','Meeting to film','Original demonstration transcript','Proposal to decision','We need a place where people can wait out of the rain. First we considered the open square. But the covered station already has seats. We will meet there tomorrow and test the route.','Carry a problem through an alternative to a decision.','Does the ending preserve the chosen place rather than restart a search?','arrive')]
cases=[]
for id,title,author,theme,brief,goal,question,mode in rows:
 cases.append(dict(id=id,title=title,author=author,theme=theme,brief=brief,goal=goal,question=question,mode=mode,text=brief if id in ['nursery','meeting'] else '',textStatus='Traditional text' if id=='nursery' else 'Original transcript' if id=='meeting' else 'Study brief · paste source text for a full-text trial',source='https://www.google.com/search?q='+__import__('urllib.parse',fromlist=['quote']).quote(author+' '+title)))
# A public-domain original; translations of other works are deliberately not conflated.
next(x for x in cases if x['id']=='williams').update(text='so much depends\nupon\n\na red wheel\nbarrow\n\nglazed with rain\nwater\n\nbeside the white\nchickens.',textStatus='Full text · 1923',source='https://www.poetryfoundation.org/poems/45502/the-red-wheelbarrow')
next(x for x in cases if x['id']=='frost').update(text='Two roads diverged in a yellow wood,\nAnd sorry I could not travel both\nAnd be one traveler, long I stood\nAnd looked down one as far as I could\nTo where it bent in the undergrowth;\n\nThen took the other, as just as fair,\nAnd having perhaps the better claim,\nBecause it was grassy and wanted wear;\nThough as for that the passing there\nHad worn them really about the same,\n\nAnd both that morning equally lay\nIn leaves no step had trodden black.\nOh, I kept the first for another day!\nYet knowing how way leads on to way,\nI doubted if I should ever come back.\n\nI shall be telling this with a sigh\nSomewhere ages and ages hence:\nTwo roads diverged in a wood, and I—\nI took the one less traveled by,\nAnd that has made all the difference.',textStatus='Full text · 1916',source='https://www.gutenberg.org/files/59824/59824-h/59824-h.htm')
# The project’s existing editorial scene score remains clearly distinguished from poem text.
x=json.load(open(P.parent/'lab-data.json'))['wygwyl']
for chapter,f in enumerate(x['films']):
 beats=[b for b in x['beats'] if b['chapter']==chapter]
 cases.insert(chapter,dict(id='wygwyl-'+f['n'],title=f['title'],author='Mark Anthony Thomas · Where You Go When You Leave',theme='Cineosis source study',brief='\n'.join(b['query'] for b in beats),text='',textStatus='Existing editorial scene score · not a transcript',goal='Develop the passage and let its last scene answer the opening.',question='Does the new cut develop the poem’s passage beyond the original forage assignments?',mode='journey',source='../wygwyl.html'))
if (P/'public-texts.json').exists():
 updates=json.load(open(P/'public-texts.json'))
 for c in cases:
  if c['id'] in updates:c.update(updates[c['id']])
(P/'tests.json').write_text(json.dumps(cases,ensure_ascii=False,indent=2))
